<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cadastro de Restaurantes</name>
   <tag></tag>
   <elementGuidId>370ecd27-ae19-421b-9344-b7fdeff6bfa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='principalAdministrador']/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3eec340f-c546-4f20-bbad-788dbb079204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>cadastroRestaurantes.php</value>
      <webElementGuid>8bb6ea0a-c34d-4fe2-98fb-51c4b8584b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cadastro de Restaurantes</value>
      <webElementGuid>b4c4ed2b-bb8f-4b8b-bed9-82b35c2b68b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;principalAdministrador&quot;)/p[1]/a[1]</value>
      <webElementGuid>3260ad0b-9c22-4589-97e2-5df2ae65cc8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='principalAdministrador']/p/a</value>
      <webElementGuid>207b49c2-3261-4f6f-bdc3-a09ee4e5eb14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cadastro de Restaurantes')]</value>
      <webElementGuid>d9807801-ba3e-44ce-bbb0-18d720944750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ações de Gerenciamento'])[1]/following::a[1]</value>
      <webElementGuid>47b102f2-1fd2-45bd-a08e-d7b31dd113fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sair'])[1]/following::a[1]</value>
      <webElementGuid>4c8bf01f-a9d8-4e8f-ab0f-e81d7096b682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cadastro de Formas de Entrega de um Restaurante'])[1]/preceding::a[1]</value>
      <webElementGuid>45faace9-6d80-4c81-a6ba-622774ccd216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cadastro de Categorias de Pratos'])[1]/preceding::a[2]</value>
      <webElementGuid>071b7ac9-0151-48a1-9470-f49d392984c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cadastro de Restaurantes']/parent::*</value>
      <webElementGuid>5d9dc163-4033-4da5-86df-a71e860b89d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'cadastroRestaurantes.php')]</value>
      <webElementGuid>f95337bd-311e-4b2b-93f9-f8049f0e8059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>1d30de6d-2588-49b2-a76c-b067b93f1ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'cadastroRestaurantes.php' and (text() = 'Cadastro de Restaurantes' or . = 'Cadastro de Restaurantes')]</value>
      <webElementGuid>8285a8c6-d3d8-4c9d-bcc4-6cb4173ada4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
