<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bairro_bairroCadastro</name>
   <tag></tag>
   <elementGuidId>6ba88aae-5182-4f6b-90c4-3fc89235ac81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bairroCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bairroCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ccbe0929-e07e-4a65-bdcd-df48f0d0d29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bairroCadastro</value>
      <webElementGuid>01207899-f39d-46a4-bfd8-af03e7230bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bairroCadastroRestaurante</value>
      <webElementGuid>60b0e015-0d01-4297-9137-7b92e80be3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a7810165-b57c-4c3f-bfc5-a1d9bc840c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>78dd6074-f437-4a01-b595-2930043f1696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bairroCadastroRestaurante&quot;)</value>
      <webElementGuid>23de105a-d8ab-4955-8eb9-0d14ac8a18fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bairroCadastroRestaurante']</value>
      <webElementGuid>7acf3c04-d8f1-48f5-83b6-30479a956661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[3]/input[3]</value>
      <webElementGuid>c825c973-35f9-4120-9022-3f93ba6c2832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>5b246aaa-4539-4774-9d1c-4c981446ce93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'bairroCadastro' and @id = 'bairroCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>06388809-2ffa-4d63-b4d5-1f2023132999</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
