<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Complemento_complementoCadastro</name>
   <tag></tag>
   <elementGuidId>77c3bcf2-eebc-451e-aa7b-53029b63c261</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#complementoCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='complementoCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>896648ec-bb25-4fb9-abe8-4b94e1f1eb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>complementoCadastro</value>
      <webElementGuid>df38ce8b-46e3-4c3e-a1e6-342a8f020cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>complementoCadastroRestaurante</value>
      <webElementGuid>7440d008-cea2-4e23-a42b-5565814b2ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99e7c4f7-fbbf-48b1-a243-8f6f3b45b1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>6ce74c84-d5c4-4bd5-a98a-3abc9cf3248a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;complementoCadastroRestaurante&quot;)</value>
      <webElementGuid>b3558981-1728-4e65-9b9b-f941e244c5fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='complementoCadastroRestaurante']</value>
      <webElementGuid>f830f1ec-725c-45d8-b1bd-ac08b4cc1bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[3]/input[2]</value>
      <webElementGuid>204c1978-6741-4bc3-85a3-580bc038bdf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>e6455238-0203-4edc-8def-994f3560e5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'complementoCadastro' and @id = 'complementoCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>f9c4d37b-74cb-47bd-8a99-cca59a4ea0ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
