<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telefone_dddTelCadastro</name>
   <tag></tag>
   <elementGuidId>70757522-d57b-462b-a068-6f1dbdb97207</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dddTelCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dddTelCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>200de838-598b-43fb-a4a2-b3cbab8c9a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dddTelCadastro</value>
      <webElementGuid>2255cdd4-4c44-4417-a8ca-b4c2ff897442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dddTelCadastroRestaurante</value>
      <webElementGuid>cc421dee-01cb-4688-a20d-be5b543aaae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56599862-7784-420f-9b4d-432098ccff4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d8c1ce43-cd23-4774-aea7-420a034be47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dddTelCadastroRestaurante&quot;)</value>
      <webElementGuid>e1e73af6-6538-42e7-afb5-ca32f928b610</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dddTelCadastroRestaurante']</value>
      <webElementGuid>f7ccf585-edae-4812-9aca-24f891914777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[5]/input</value>
      <webElementGuid>86070bec-a7f0-436c-84f9-5180f1b649bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>fed2ecab-5c97-48ed-8381-a46e0d299b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dddTelCadastro' and @id = 'dddTelCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>08d657ed-1fe4-4ea0-a708-e58c39d90292</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
