<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Horrio de Funcionamento_horaInicio</name>
   <tag></tag>
   <elementGuidId>bd5f7c40-3629-48e0-94f5-13240ab770ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#horaInicioRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='horaInicioRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07f2a749-d96f-495a-b37e-7a2d151bcfbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>horaInicio</value>
      <webElementGuid>9d05f3ec-4825-4880-af73-c870ff0979be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>horaInicioRestaurante</value>
      <webElementGuid>aedf2bb3-aadc-4048-9c44-2c06225caf0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b86fd7d-12b3-429b-b745-3b84b7c96a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>210f2ef8-3d82-4a79-8114-a75b877b8223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>4458883f-bf48-4043-a369-34f607a052b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>00:00:00</value>
      <webElementGuid>f1241e94-af7e-49d2-8d55-e57a9b0dc495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;horaInicioRestaurante&quot;)</value>
      <webElementGuid>d18e4463-91e4-42fa-8721-8b353c95be67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='horaInicioRestaurante']</value>
      <webElementGuid>837296c1-1d20-463e-934e-93243d2161c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[6]/input</value>
      <webElementGuid>deb2dc3e-40be-4ded-9be1-ed9a9b7494a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>8e66f1b4-1c70-4cab-9752-ab9bf02167a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'horaInicio' and @id = 'horaInicioRestaurante' and @type = 'text']</value>
      <webElementGuid>ff59a1ed-b2e3-45e6-a50f-8568340215ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
