<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RuaAv_ruaCadastro</name>
   <tag></tag>
   <elementGuidId>b72d1529-81cb-440f-98ff-c098791451a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ruaCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ruaCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecb98090-21c7-4966-a51f-9d4f1785ef57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ruaCadastro</value>
      <webElementGuid>56c83b35-e4a0-41f2-8449-0b4899d88241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ruaCadastroRestaurante</value>
      <webElementGuid>f7b40014-9faa-4684-a590-0ada9bb9cf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f672c77e-249a-4720-8b63-78a9ea50f606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>107ceeaf-bbc7-4d7b-8022-f431dc7e0751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ruaCadastroRestaurante&quot;)</value>
      <webElementGuid>d1fe82c4-402a-44f4-a81e-47a5cd14f037</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ruaCadastroRestaurante']</value>
      <webElementGuid>56e569d6-dd1b-4335-bf43-8fdc42ad5212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[2]/input</value>
      <webElementGuid>ba6cfc57-e6ce-45cc-a232-a897ce58eac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>366f36b7-ffd1-4ad9-8352-65f21b62443f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ruaCadastro' and @id = 'ruaCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>a8f9536a-3865-4419-afa6-cadc15e8b698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
