<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ALAPAMBACEDFESGOMAMTMSMGPAPBPRPEPIRR_4d941d</name>
   <tag></tag>
   <elementGuidId>fededb5f-3fce-40d4-be27-aa055526c3a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;estadoCadastro&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='estadoCadastro']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7240812d-dd82-4414-b77a-4432fb4f0f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uf</value>
      <webElementGuid>1ac0cf07-7d46-475c-a642-6100551f0a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>estadoCadastro</value>
      <webElementGuid>04578f79-516e-4444-8f0d-0db4496509ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										AL
										AP									
										AM									
										BA									
										CE									
										DF									
										ES									
										GO									
										MA									
										MT									
										MS									
										MG									
										PA									
										PB									
										PR									
										PE									
										PI									
										RR									
										RO									
										RJ									
										RN									
										RS									
										SC									
										SP									
										SE									
										TO									 
							</value>
      <webElementGuid>bd09266a-9e3c-4842-a119-bd784db87d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formularioCadastroRestaurante&quot;)/div[4]/select[@class=&quot;uf&quot;]</value>
      <webElementGuid>7d608e02-900b-4404-92fa-0226b2983e73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='estadoCadastro']</value>
      <webElementGuid>5f901474-38b0-491f-ba77-df6d312fa047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[4]/select</value>
      <webElementGuid>d5adb9b5-e4e9-461b-b02f-1c4455de7d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*UF:'])[1]/following::select[1]</value>
      <webElementGuid>98c8d721-a3de-439c-9b49-4b2eaaf1a593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Cidade:'])[1]/following::select[1]</value>
      <webElementGuid>424b20f8-fd27-4c2f-bde2-c557600636ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Telefone:'])[1]/preceding::select[1]</value>
      <webElementGuid>1d5149c4-7c3e-44b8-b660-5acacc09edba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2dbb1e9d-219f-4ac3-aaf6-b05f6c518e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'estadoCadastro' and (text() = '
										AL
										AP									
										AM									
										BA									
										CE									
										DF									
										ES									
										GO									
										MA									
										MT									
										MS									
										MG									
										PA									
										PB									
										PR									
										PE									
										PI									
										RR									
										RO									
										RJ									
										RN									
										RS									
										SC									
										SP									
										SE									
										TO									 
							' or . = '
										AL
										AP									
										AM									
										BA									
										CE									
										DF									
										ES									
										GO									
										MA									
										MT									
										MS									
										MG									
										PA									
										PB									
										PR									
										PE									
										PI									
										RR									
										RO									
										RJ									
										RN									
										RS									
										SC									
										SP									
										SE									
										TO									 
							')]</value>
      <webElementGuid>ff19cc7b-0ca2-4522-8ccf-c7074e74e561</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
