<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entrar_login</name>
   <tag></tag>
   <elementGuidId>d652a5e4-1840-44e0-9fa5-2d26439fb567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formLoginUsuario</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formLoginUsuario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72a040fd-ed99-44da-a212-a29d6556868f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b58b1587-bb71-41d6-abb5-14df53ce87e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formLoginUsuario</value>
      <webElementGuid>d7d713ae-31b5-4a7f-8d6d-3186b430f081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8acc4dac-5663-460a-afb5-bfef76d587de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Usuário</value>
      <webElementGuid>2fe03e83-4cbd-4085-bf17-901efdada6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>0b04a950-7b35-47a8-b933-8bc38eeebf25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formLoginUsuario&quot;)</value>
      <webElementGuid>73e1607f-827c-40da-af9d-083eae71d3f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formLoginUsuario']</value>
      <webElementGuid>79a236ac-5930-4252-b65d-dc8df9bd5030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioLoginUsuario']/div/input</value>
      <webElementGuid>b6b26cf1-92eb-4f99-8507-d5a78950e28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8557d9ec-d003-40c8-bb4f-dc23475fc81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'formLoginUsuario' and @placeholder = 'Usuário' and @name = 'login']</value>
      <webElementGuid>93c30fb6-bfd8-4542-a21d-b1963dbd43b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
