<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mdia_tamanhos_1</name>
   <tag></tag>
   <elementGuidId>8a811702-85f2-4e21-9561-e82008f48823</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='tamanhos[]'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td:nth-of-type(2) > #checkTamanhoPrato > div > input[name=&quot;tamanhos[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>debccb56-54df-4146-a67b-20a5ed0c7312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ead97500-bb43-407d-b8d8-4e02c37e8d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tamanhos[]</value>
      <webElementGuid>d9255b40-6d05-4903-af52-e63cfc02dfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>3f28cfff-3324-4496-bebc-45e2690bf7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Chocolate</value>
      <webElementGuid>36e633d6-0549-4ba7-8247-84f335d5b085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formularioAdicionarCarrinho&quot;)/table[@id=&quot;tabelaCardapio&quot;]/tbody[1]/tr[4]/td[2]/div[@id=&quot;checkTamanhoPrato&quot;]/div[1]/input[1]</value>
      <webElementGuid>6c21a556-0b4d-41c9-a5a3-a2eea0075431</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='tamanhos[]'])[4]</value>
      <webElementGuid>9eb14254-81b1-4b58-83fe-27a5daa3699a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='checkTamanhoPrato']/div/input)[4]</value>
      <webElementGuid>67f402c5-c0b1-4a39-8363-6a33bdca6e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/div/input</value>
      <webElementGuid>2bdde96f-83f7-43c4-8aac-d3b749cd38c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'tamanhos[]' and @title = 'Chocolate']</value>
      <webElementGuid>45705e8e-2c27-42b7-9b9c-ff149085e353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
