<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mdia_tamanhos_1_2</name>
   <tag></tag>
   <elementGuidId>28c9c711-cbf7-4f51-9b6c-21ae5a8895a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='tamanhos[]'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(5) > td:nth-of-type(2) > #checkTamanhoPrato > div > input[name=&quot;tamanhos[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99bce0f4-8ed7-4058-b740-23f2246a49fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8536917e-6189-4c6d-8393-97bfd80a7d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tamanhos[]</value>
      <webElementGuid>ecbe0605-857a-4884-98ad-86066f4feaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>f31523e1-362f-4d8f-935b-ea2282072129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marguerita</value>
      <webElementGuid>06958694-5fcc-4f73-aef3-2efe3a7479bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formularioAdicionarCarrinho&quot;)/table[@id=&quot;tabelaCardapio&quot;]/tbody[1]/tr[5]/td[2]/div[@id=&quot;checkTamanhoPrato&quot;]/div[1]/input[1]</value>
      <webElementGuid>4a1b699c-deb6-4cc8-83cb-3fccd46406a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='tamanhos[]'])[5]</value>
      <webElementGuid>af24c7d7-0f0f-4d0d-9587-f5542f4cb02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='checkTamanhoPrato']/div/input)[5]</value>
      <webElementGuid>4edc64c7-d435-44df-9d64-4e0ef27d6111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/div/div/input</value>
      <webElementGuid>8da5c230-3503-4622-bb8d-4bd857c61de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'tamanhos[]' and @title = 'Marguerita']</value>
      <webElementGuid>307e1307-9ace-4b9e-a2e3-ccaf6c112a06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
