<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail_emailCadastro</name>
   <tag></tag>
   <elementGuidId>b669f2c1-8607-404c-b3c5-bb346a134624</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailCadastroUsuario']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#emailCadastroUsuario</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>306cc204-c15e-4342-8a72-2c2e4b97e888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emailCadastro</value>
      <webElementGuid>2807abb0-dc2f-47e0-bf3e-4efadaa7225d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailCadastroUsuario</value>
      <webElementGuid>de2813de-aa70-4428-81e2-b42b9bd5f56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>73c47065-8655-481a-881f-e1213cee0edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>7e1a3413-69a5-407e-a83f-c2ff86a1103c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d03622b7-5e13-4e10-8072-c953c8d3a4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailCadastroUsuario&quot;)</value>
      <webElementGuid>cd110fb2-7949-4155-94a5-8ba75edb4089</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailCadastroUsuario']</value>
      <webElementGuid>bde142d7-cdd8-47a4-b705-19b0a23f80a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div[2]/input</value>
      <webElementGuid>f23e0a5f-1949-41a4-ad14-1019e3e0ad56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a82cd759-c2a3-4e69-a834-4ac03dd21ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'emailCadastro' and @id = 'emailCadastroUsuario' and @type = 'email']</value>
      <webElementGuid>919dfe7b-a7ee-46dc-9493-d853e7c66550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
