<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Senha_senhaCadastro</name>
   <tag></tag>
   <elementGuidId>0c23ba56-06ef-4044-a0f4-a6162e6f7f45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='senhaCadastroUsuario']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#senhaCadastroUsuario</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a35fe61-afef-4ca6-9a7d-14364b002e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>senhaCadastro</value>
      <webElementGuid>b4f1f95b-5646-4105-84c1-555c9316c704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>senhaCadastroUsuario</value>
      <webElementGuid>0f819efc-da72-44d2-88bb-5397a3f8a835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>bd3317e3-542d-4a56-924b-7b317390df41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d162732a-291e-4c04-9651-532145a39656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d4f99cee-441a-4b55-98a4-9b4a33819c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;senhaCadastroUsuario&quot;)</value>
      <webElementGuid>4847e1c7-370e-40a7-84e8-91d771c234e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='senhaCadastroUsuario']</value>
      <webElementGuid>c62d921b-2929-40e5-a191-b8fc024d730e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div[5]/input</value>
      <webElementGuid>f540221a-ed15-4299-b68d-5cfb5404df3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>5805cf8a-41c6-4f0e-9f82-c208e9e32a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'senhaCadastro' and @id = 'senhaCadastroUsuario' and @type = 'password']</value>
      <webElementGuid>c847fcce-12cd-489a-8561-76b8d3f8ab49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
