<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RuaAv_ruaCadastro</name>
   <tag></tag>
   <elementGuidId>eb36f1b7-398a-44e1-96ad-d1790def4f76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ruaCadastroEndereco']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ruaCadastroEndereco</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f40384e-738e-4afd-8908-264a25546504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ruaCadastro</value>
      <webElementGuid>71163862-ead2-4c00-b60c-efb2db0892d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ruaCadastroEndereco</value>
      <webElementGuid>1334a5d0-181e-475e-bf90-74859d03c83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7bea337-4a65-4354-b955-8d769c3ae4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>1a6760c7-3b5e-4424-8657-e0a26def92a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0f1ddfa0-8259-4820-941b-ce1b6c922552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ruaCadastroEndereco&quot;)</value>
      <webElementGuid>5f6a994f-f5a0-43a8-bf6d-e10e142b381c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ruaCadastroEndereco']</value>
      <webElementGuid>66566981-16b5-47bf-b8ed-11055da5cb84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div[7]/div/input</value>
      <webElementGuid>1d2b1d8b-4819-4d8e-b621-e3baed515fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>ec293a4f-a664-4078-8c5e-155613c6c78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ruaCadastro' and @id = 'ruaCadastroEndereco' and @type = 'text']</value>
      <webElementGuid>7f2fc17a-7b04-4229-9fb4-4747aeee0d79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
