<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero_numeroCadastro</name>
   <tag></tag>
   <elementGuidId>2db274c6-a49c-4d35-9946-074872b9b6f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numeroCadastroEndereco']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#numeroCadastroEndereco</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f80f394-0b50-4975-af61-17984be87588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numeroCadastro</value>
      <webElementGuid>03c2f502-be41-49fe-bec8-59a0c9ce3cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numeroCadastroEndereco</value>
      <webElementGuid>bc7cd002-7dd5-426d-828d-dce47043bd52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a413d82-7d61-45e0-9c7c-3ce7deb3d7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>12c770d2-6c4d-4a5d-992e-f6f7e0788b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f01c8d7a-c08a-4a4d-a113-a2b7bd702fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numeroCadastroEndereco&quot;)</value>
      <webElementGuid>9352ed1b-599b-42cd-a917-cbef0d8120e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numeroCadastroEndereco']</value>
      <webElementGuid>8bddf9c9-ede3-45fd-a406-828af2278cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div[7]/div[2]/input</value>
      <webElementGuid>76031ba1-419d-4fbe-8238-dcac7df423d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/input</value>
      <webElementGuid>1433ecbd-c337-4afd-8562-ce34ca4377a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'numeroCadastro' and @id = 'numeroCadastroEndereco' and @type = 'text']</value>
      <webElementGuid>41ea117d-9be6-4f97-b826-4854024f80bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
