<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cidade_cidadeCadastro</name>
   <tag></tag>
   <elementGuidId>78f1f8fc-ee60-48f3-9725-388fa7ad73ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cidadeCadastroEndereco']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cidadeCadastroEndereco</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4753938e-844a-456f-b67d-59e61aef31b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cidadeCadastro</value>
      <webElementGuid>e7704fa8-1b04-4b6e-9241-d1fca83a354a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cidadeCadastroEndereco</value>
      <webElementGuid>d7c23ff7-c9ba-4e6e-9058-336cbaa70b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97d01b7c-5182-47c8-8991-0460b91d8119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>ee5e8f50-973e-41bb-b8af-3cf9c84dd007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b553a3ae-a67b-440f-8541-b69a8008f56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cidadeCadastroEndereco&quot;)</value>
      <webElementGuid>b3c52ec4-eb5d-43a6-9181-880a4c567f5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cidadeCadastroEndereco']</value>
      <webElementGuid>3945f202-53d9-403a-96d6-c56f8f4eb36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div[9]/div/input</value>
      <webElementGuid>21b25b51-dd97-4607-ba64-508f2bc23411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>a5ee92e2-70b3-4525-9954-d664c8cb48f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cidadeCadastro' and @id = 'cidadeCadastroEndereco' and @type = 'text']</value>
      <webElementGuid>4cb88fa8-50ec-4827-a7ec-e3405fc07d45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
