<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ALAPAMBACEDFESGOMAMTMSMGPAPBPRPEPIRR_4d941d</name>
   <tag></tag>
   <elementGuidId>d3fe96f6-2e29-491d-99af-4bc7e53b56d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='estadoCadastro']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;estadoCadastro&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4df3337d-bf17-4e34-8ce5-05a011e521c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>estadoCadastro</value>
      <webElementGuid>882eab45-faa9-4867-8679-3d09e1edb7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uf form-control</value>
      <webElementGuid>c55516b4-9b68-4af3-abee-766dbc0b201c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
											AL
											AP									
											AM									
											BA									
											CE									
											DF									
											ES									
											GO									
											MA									
											MT									
											MS									
											MG									
											PA									
											PB									
											PR									
											PE									
											PI									
											RR									
											RO									
											RJ									
											RN									
											RS									
											SC									
											SP									
											SE									
											TO	
										</value>
      <webElementGuid>3bfc7ded-3e9f-423d-bda7-20dbdda607d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formularioCadastroUsuario&quot;)/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group col-md-6&quot;]/select[@class=&quot;uf form-control&quot;]</value>
      <webElementGuid>93e07c27-a2f1-4200-89b4-61d7e045c029</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='estadoCadastro']</value>
      <webElementGuid>2d837303-2d02-470f-a51d-788c003a64c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div[9]/div[2]/select</value>
      <webElementGuid>a9e5a37f-e57f-4099-b3b6-94a686cfdc25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UF'])[1]/following::select[1]</value>
      <webElementGuid>7fc88dc2-5d5d-4dfa-9f2a-d13198ad7d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cidade'])[1]/following::select[1]</value>
      <webElementGuid>2af5d2e7-b6ed-485f-8abe-934749efba28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cadastrar'])[1]/preceding::select[1]</value>
      <webElementGuid>13b846d7-1cca-41c4-967b-15a9bcf88bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ef997829-9eaa-445c-b0b8-3f8313acb97a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'estadoCadastro' and (text() = '
											AL
											AP									
											AM									
											BA									
											CE									
											DF									
											ES									
											GO									
											MA									
											MT									
											MS									
											MG									
											PA									
											PB									
											PR									
											PE									
											PI									
											RR									
											RO									
											RJ									
											RN									
											RS									
											SC									
											SP									
											SE									
											TO	
										' or . = '
											AL
											AP									
											AM									
											BA									
											CE									
											DF									
											ES									
											GO									
											MA									
											MT									
											MS									
											MG									
											PA									
											PB									
											PR									
											PE									
											PI									
											RR									
											RO									
											RJ									
											RN									
											RS									
											SC									
											SP									
											SE									
											TO	
										')]</value>
      <webElementGuid>7d3b9031-df82-4bd6-8e23-495bc290b67d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
