<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entrar_senha</name>
   <tag></tag>
   <elementGuidId>ae445a43-8796-4c63-bfbd-e34ca63047c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formSenhaUsuario</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formSenhaUsuario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98827a33-a64b-47ed-8543-d782c9f33ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>35528063-d378-421d-a76b-1144efaccac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formSenhaUsuario</value>
      <webElementGuid>a2d3d2f1-6725-4e73-b1a8-b183375d3b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>183aa2d9-b558-42cd-8275-a3f7b087783b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Senha</value>
      <webElementGuid>72f9c5fa-98ce-4001-b764-8a834abae434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>senha</value>
      <webElementGuid>17b8249e-9892-48ff-9a3c-b16daa66b200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wfd-id</name>
      <type>Main</type>
      <value>id1</value>
      <webElementGuid>6b1e955b-1dbc-4f27-a844-d00aeca517fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSenhaUsuario&quot;)</value>
      <webElementGuid>321bd54c-3cfc-4a53-a9ea-b744d3423ca0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formSenhaUsuario']</value>
      <webElementGuid>bd6788e3-d516-415f-a345-552191475359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioLoginUsuario']/div[2]/input</value>
      <webElementGuid>e63f043a-ae8d-4ee5-9ba0-a39dbe9e9ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>760aea4e-795a-4435-b871-6692c9bed7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'formSenhaUsuario' and @placeholder = 'Senha' and @name = 'senha']</value>
      <webElementGuid>68c5eed3-cbac-4748-a094-b84ad3937c47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
