<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_California</name>
   <tag></tag>
   <elementGuidId>84e2a967-e6dc-474a-a70d-475d0cdf24d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divListaPizzarias']/ul/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d8c223e5-5fa0-4914-be46-d3531e423263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item list-group-item-action</value>
      <webElementGuid>3b9c546f-aff1-47ec-b4d8-3c45897ff00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?p=2</value>
      <webElementGuid>1aee5d2e-a15c-4584-be6d-bb943f412230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>California</value>
      <webElementGuid>55b6c3df-855a-484d-be8e-bfa4b6c3eaf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divListaPizzarias&quot;)/ul[@class=&quot;list-group list-group-flush&quot;]/a[@class=&quot;list-group-item list-group-item-action&quot;]</value>
      <webElementGuid>0c366d1b-673b-4779-b68e-bb9f60950fb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divListaPizzarias']/ul/a[2]</value>
      <webElementGuid>81fcc625-993c-47be-a8df-4fc57c61f679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'California')]</value>
      <webElementGuid>6e691faa-daa5-4198-b9da-234f3ea49d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Papillon'])[1]/following::a[1]</value>
      <webElementGuid>d82b97f8-5d23-459b-afb7-26f6a345ebcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restaurantes'])[1]/following::a[2]</value>
      <webElementGuid>22e161d6-0237-47e6-81b9-539197ab1b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bonna Pizza'])[1]/preceding::a[1]</value>
      <webElementGuid>c464adeb-49f8-44c8-8649-da6d43ed20cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prediletta'])[1]/preceding::a[2]</value>
      <webElementGuid>4643db57-58bd-4093-b128-0e7799a3b9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='California']/parent::*</value>
      <webElementGuid>43a44a1f-6a74-46bb-8742-7d3ab81cb2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?p=2')]</value>
      <webElementGuid>b7481bc3-64f1-4c41-8255-690d460134d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/a[2]</value>
      <webElementGuid>f04bdcb3-718e-4e1b-a2e2-ca0420998a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?p=2' and (text() = 'California' or . = 'California')]</value>
      <webElementGuid>9814fd73-24c2-4a53-bb87-a48c55d24e68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
