<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gerenciar Restaurantes</name>
   <tag></tag>
   <elementGuidId>ef8e019f-e5ab-450e-b280-a9786e3cfaa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(10) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='principalAdministrador']/p[10]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>39bf4b48-698c-43f1-b01b-3741011f9451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>controleRestaurantes.php</value>
      <webElementGuid>21a4ef7b-f437-4eaf-9066-87f67f67a917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gerenciar Restaurantes</value>
      <webElementGuid>bffd353b-e6de-4c2c-be5f-4e728f530672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;principalAdministrador&quot;)/p[10]/a[1]</value>
      <webElementGuid>919277d5-2226-4a86-b74e-06ced8106afc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='principalAdministrador']/p[10]/a</value>
      <webElementGuid>8e05da8c-68f0-4b84-bc0f-909c31613732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gerenciar Restaurantes')]</value>
      <webElementGuid>e135caec-6636-4fdb-8dab-435a0351b28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gerenciar Usuários'])[1]/following::a[1]</value>
      <webElementGuid>c9798c8c-63c8-45e9-ad7e-400f5a7954a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gerenciar Extras'])[1]/following::a[2]</value>
      <webElementGuid>f1152d98-451e-4258-ad54-e116578185fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'principalAdministrador', '&quot;', ')/p[10]/a[1]')])[1]/preceding::a[1]</value>
      <webElementGuid>545eb018-8405-4c2d-9d4d-3a8602d2c6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gerenciar Restaurantes']/parent::*</value>
      <webElementGuid>f8257dd6-161f-4581-bee7-65693ca0a509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'controleRestaurantes.php')]</value>
      <webElementGuid>292cf829-5971-4252-8066-9736d6c449f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]/a</value>
      <webElementGuid>b271f1e2-1d69-400e-81de-3e4113af0e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'controleRestaurantes.php' and (text() = 'Gerenciar Restaurantes' or . = 'Gerenciar Restaurantes')]</value>
      <webElementGuid>80fdf7ed-056b-448c-b5bd-9676b126d5cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
