<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cidade</name>
   <tag></tag>
   <elementGuidId>f3d31fc5-a43b-457d-b730-e2357aa1ee67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cidadeCadastro</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cidadeCadastro']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23bf741f-b343-466a-8bf5-519cb443135a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cidadeCadastro</value>
      <webElementGuid>74a9006c-5559-4f97-9a94-cfb354c164c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cidadeCadastro</value>
      <webElementGuid>1bf8839c-fcae-4c66-aae0-ee1c563d0f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e15d2395-f9a6-443f-8d80-21b8182c0d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>14dd8a09-e57e-401e-be4e-d95aa8710e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Nova Friburgo</value>
      <webElementGuid>3216dd9b-6909-4ead-a838-886f5dc03e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cidadeCadastro&quot;)</value>
      <webElementGuid>18e7f1c7-41bf-4959-a7df-542ea50e1ca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cidadeCadastro']</value>
      <webElementGuid>9ffa80b5-db83-4928-ad31-a33770ba1231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastro']/div[4]/input</value>
      <webElementGuid>760dc26b-3160-49d1-b390-838f9b96a8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>a66c764d-7a0a-415d-96a4-94d1f23a1f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cidadeCadastro' and @id = 'cidadeCadastro' and @type = 'text']</value>
      <webElementGuid>987b2ea1-d950-4cf6-b66b-c7fec212b391</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
