<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Voltar</name>
   <tag></tag>
   <elementGuidId>4e12d711-0996-4a8c-938d-fce122917dab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='doisSabores']/form/table/tbody/tr[6]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b5b00a7-6276-4a3f-96fb-9b46b932ee0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?p=2</value>
      <webElementGuid>fb1c547e-8111-4505-9579-07a9945da38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Voltar</value>
      <webElementGuid>7551f7f6-e1cd-437d-b446-01591c020361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doisSabores&quot;)/form[1]/table[1]/tbody[1]/tr[6]/td[1]/a[1]</value>
      <webElementGuid>2b29beec-6039-4a56-b099-12802f791714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='doisSabores']/form/table/tbody/tr[6]/td/a</value>
      <webElementGuid>4b4925c8-4691-48db-bd39-d0850ed5b416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Voltar')]</value>
      <webElementGuid>bee6e4b8-3030-4c82-a241-9bbb416892b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Segundo sabor:'])[1]/following::a[1]</value>
      <webElementGuid>27c39065-b1e1-4ac6-9e52-895a5de9ff1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primeiro Sabor:'])[1]/following::a[1]</value>
      <webElementGuid>a148e85e-8cd2-4a12-acbc-74dc011286d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'doisSabores', '&quot;', ')/form[1]/table[1]/tbody[1]/tr[6]/td[1]/a[1]')])[1]/preceding::a[1]</value>
      <webElementGuid>ed6f6f50-f500-4a3e-b038-793f104ec014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Voltar']/parent::*</value>
      <webElementGuid>e588fabb-90ae-4fe6-8938-21e5f3bdc7f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?p=2')]</value>
      <webElementGuid>629c57b7-9a97-495b-a1b4-d51d1993db3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>1245a969-d976-4333-8173-27dcdd23c6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?p=2' and (text() = 'Voltar' or . = 'Voltar')]</value>
      <webElementGuid>17d9ec8d-3c21-4241-a41d-2295e5bbbb97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
