<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero de pratos_numeroDePratos</name>
   <tag></tag>
   <elementGuidId>603988f2-0980-4bf6-b9da-f0ae14dc0a06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;numeroDePratos&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='numeroDePratos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4ab05d1-ffcf-4010-9dc6-3b6437ce295c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a191b863-ddda-494e-a506-b9b010df06fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numeroDePratos</value>
      <webElementGuid>4d76634b-4abb-4b5a-898f-7e45e0826ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>96574052-81e1-43d9-b86e-5034be5e0720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cfbd96c4-0b15-4fae-b101-62eca2ea9a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;restauranteCardapio&quot;)/form[1]/input[1]</value>
      <webElementGuid>13049da7-897c-4197-b10c-ab5b76eb358d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='numeroDePratos']</value>
      <webElementGuid>a48acf00-3412-444e-bb45-2ee72204976b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='restauranteCardapio']/form/input</value>
      <webElementGuid>348b957f-093e-4761-97dd-993ff2e56896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bd7edc9a-e33a-4037-b80c-57f53babe678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'numeroDePratos']</value>
      <webElementGuid>f6816675-fc22-4a26-b250-05b705a96538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
