<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_R_precoPratoMaior0</name>
   <tag></tag>
   <elementGuidId>a7d5cb5d-492d-42f3-bcbb-bf4d587e3ab5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;precoPratoMaior0&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='precoPratoMaior0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a630882-894d-4837-970e-4d0896601257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78f5eff1-46ad-4f88-8e0a-a287c84b080e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>precoPratoMaior0</value>
      <webElementGuid>4d070981-d37a-40d3-98ec-290627cd8847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>06dab209-d520-4b22-978e-c251ebba8276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabelaCadastroTamanhosCardapio&quot;)/tbody[1]/tr[4]/td[2]/input[1]</value>
      <webElementGuid>34ed59a7-c016-4278-afc6-f67037e56f40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='precoPratoMaior0']</value>
      <webElementGuid>fb30f87a-6da8-45c2-b5ed-08de03bf1848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tabelaCadastroTamanhosCardapio']/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>3c195560-3e65-438c-822d-be931ae58632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>c1367d3b-a172-4ba4-b710-1c30639ae844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'precoPratoMaior0']</value>
      <webElementGuid>2cd90edf-f8ce-4e20-b6aa-d120c0bebfd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
