<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_R_tamanhoPratoMaior0</name>
   <tag></tag>
   <elementGuidId>d7799f9c-c9f5-4b45-8425-5f38636fb837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tamanhoPratoMaior0&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tamanhoPratoMaior0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01da10ca-e1d4-4cfa-b1b5-ecc2554c1e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tamanhoPratoMaior0</value>
      <webElementGuid>5e32688a-69e7-4aaf-9e63-19d4fa81962f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2038552f-3516-4c3e-8824-af037b87773c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>715c1633-d77f-4486-ae9d-b46a8dc45f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabelaCadastroTamanhosCardapio&quot;)/tbody[1]/tr[4]/td[1]/input[1]</value>
      <webElementGuid>23c092d5-5e9f-48af-9f00-0e13be903d4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tamanhoPratoMaior0']</value>
      <webElementGuid>0a8a6cee-006f-48c2-87f5-f2b780c78488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tabelaCadastroTamanhosCardapio']/tbody/tr[4]/td/input</value>
      <webElementGuid>e25725c3-daeb-4164-bb02-45aeb2782687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>9e8cd827-19fa-413e-bf90-1633e6adab25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'tamanhoPratoMaior0' and @type = 'text']</value>
      <webElementGuid>d30395cf-6f1a-4bd0-bba7-2878e5476076</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
