<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_R_precoPratoMedio0</name>
   <tag></tag>
   <elementGuidId>21d479ef-5509-4f23-9657-71a6c718b342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;precoPratoMedio0&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='precoPratoMedio0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>393059c7-92fc-426f-89f6-39157c17f767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d74e51b-7ee6-4006-8182-1829ec18d08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>precoPratoMedio0</value>
      <webElementGuid>e621631f-7cdd-44c5-83b6-eafb44a8728b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>1487baf7-fc02-4b05-ab0b-b2c8241f237c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabelaCadastroTamanhosCardapio&quot;)/tbody[1]/tr[3]/td[2]/input[1]</value>
      <webElementGuid>44b13942-7fef-4e42-a4c4-304f645bed8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='precoPratoMedio0']</value>
      <webElementGuid>1c6bde0e-0a00-4029-9f02-167de18bfc55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tabelaCadastroTamanhosCardapio']/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>733b982a-d82d-4de7-a000-87d1514599e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>f2de134b-61ef-433c-82c6-e2812b75f5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'precoPratoMedio0']</value>
      <webElementGuid>d1dc5474-b3cd-4961-9a99-244e62887c60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
