<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Preo de cada tamanho_tamanhoPratoMenor0</name>
   <tag></tag>
   <elementGuidId>6efcda27-e6f1-4473-9ea9-c1d42e663621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tamanhoPratoMenor0&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tamanhoPratoMenor0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2f06ed3-085d-4322-bd20-2def50bf66d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tamanhoPratoMenor0</value>
      <webElementGuid>68dab142-ac4a-4b7e-aee0-b6895a9efbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0cf2e921-dce9-4a48-98e5-48fc8af48647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>0e236742-8dde-41de-8ba5-7ce97f1f025d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabelaCadastroTamanhosCardapio&quot;)/tbody[1]/tr[2]/td[1]/input[1]</value>
      <webElementGuid>df5758a8-d91b-4a79-ba82-3cd9b4fac14e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tamanhoPratoMenor0']</value>
      <webElementGuid>e545c29c-c273-4c7d-9f5b-ba7b2011f89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tabelaCadastroTamanhosCardapio']/tbody/tr[2]/td/input</value>
      <webElementGuid>fe7a2f83-acaa-4b23-904d-755b5c3f56e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>77703072-94f0-49e2-b113-d7cd017ebb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'tamanhoPratoMenor0' and @type = 'text']</value>
      <webElementGuid>0c389a0f-d6dc-40ab-9b31-5f2982eb6cb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
