<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_R_tamanhoPratoMedio0</name>
   <tag></tag>
   <elementGuidId>83ac04c5-755e-4358-9544-7f69ef04f222</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tamanhoPratoMedio0&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tamanhoPratoMedio0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45bf2a9c-c65f-4639-a948-3e411fb840b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tamanhoPratoMedio0</value>
      <webElementGuid>50718b8f-0477-4bb7-9e1a-7a9b36023e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2ed6a87-eed1-43d0-bb3b-ac8dfd42f182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>61d2c072-88ea-469c-85e4-f5585d3e81ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabelaCadastroTamanhosCardapio&quot;)/tbody[1]/tr[3]/td[1]/input[1]</value>
      <webElementGuid>66685a02-bdf7-4592-97d9-81037e0b7a89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tamanhoPratoMedio0']</value>
      <webElementGuid>57b3939d-5dd8-4e22-b0f3-0a662f4a4ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tabelaCadastroTamanhosCardapio']/tbody/tr[3]/td/input</value>
      <webElementGuid>9dd5fa0e-07fd-4d9f-817d-846335ce345e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>4121ab75-3b4b-44e8-b198-4290942a41c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'tamanhoPratoMedio0' and @type = 'text']</value>
      <webElementGuid>b6a69463-10a9-433d-aff2-5b89535e6533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
