<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_R_precoPratoMenor0</name>
   <tag></tag>
   <elementGuidId>66e65085-2c53-4a4c-83de-e61b0b0eb0eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;precoPratoMenor0&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='precoPratoMenor0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94d6f102-1def-4d7c-ba43-4324d54c6cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20769f1e-75d6-47d6-b112-f81bbe1f5606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>precoPratoMenor0</value>
      <webElementGuid>b68d8003-618f-4963-b8e9-911e55d8680b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>cca0cf8c-9272-4f34-9c56-061dc4957520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabelaCadastroTamanhosCardapio&quot;)/tbody[1]/tr[2]/td[2]/input[1]</value>
      <webElementGuid>e4ec4f30-7e3f-4a30-873f-b4356ef906e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='precoPratoMenor0']</value>
      <webElementGuid>a59f8f9f-fd69-42fc-9943-897c672b503b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tabelaCadastroTamanhosCardapio']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>935279be-e43e-40c8-8f8b-6aad88498db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>94468999-6b11-40c0-9fca-9ed2baa8b107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'precoPratoMenor0']</value>
      <webElementGuid>7139976f-ced5-4080-a6dc-e9ea2a99559a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
