<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descricao do prato_descricaoPrato0</name>
   <tag></tag>
   <elementGuidId>76c3e612-d1d3-43f7-8ece-eaeae50fe6b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;descricaoPrato0&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='descricaoPrato0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7075e74-5302-4001-af4d-4a2bb0183981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>descricaoPrato0</value>
      <webElementGuid>fad8ba84-3a09-44b0-9391-0ff3f012aa72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb01d2b2-4934-4180-b19d-d4fd8ebe66ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>f90d9f46-094c-4faa-9149-ca4982b8889f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descricaoPratoFormularioCardapio&quot;)/input[1]</value>
      <webElementGuid>456f59f1-b6e2-4bb5-9010-506d8fc0317e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='descricaoPrato0']</value>
      <webElementGuid>e01afa3c-643d-4aa3-9304-adc258017c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='descricaoPratoFormularioCardapio']/input</value>
      <webElementGuid>f45add8c-d409-4127-8d33-2d29bbfb51a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>18fc5cb0-097c-4407-a164-546fe52adc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'descricaoPrato0' and @type = 'text']</value>
      <webElementGuid>d88908b7-0e96-4e49-960f-32e68c73df18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
