<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1        2        3        4        _e414dd</name>
   <tag></tag>
   <elementGuidId>34a926e2-97f2-47d9-a376-a4c5055b2443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;quantidade&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='quantidade']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ea6ab3aa-7742-4615-9ec9-192eba094041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantidade</value>
      <webElementGuid>f79a87dd-327b-481a-b8bd-a85a7cadbdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        1
        2
        3
        4
        5
        6
        7
        8
        9
        10
    </value>
      <webElementGuid>1a17d1a8-82b5-488d-b8a2-8c06671b256d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formularioDoisSabores&quot;)/table[1]/tbody[1]/tr[6]/td[2]/select[1]</value>
      <webElementGuid>4b4f08bd-7635-47ea-aa4c-326fde430923</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='quantidade']</value>
      <webElementGuid>b6ef0339-ed8b-4238-b684-601e6fe18d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioDoisSabores']/table/tbody/tr[6]/td[2]/select</value>
      <webElementGuid>4533d556-4b5e-48c5-9f91-191ad6244258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantidade:'])[1]/following::select[1]</value>
      <webElementGuid>b3907beb-26d5-4299-9455-b136d4bebf7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R$'])[1]/following::select[1]</value>
      <webElementGuid>9987a4a0-7f8c-426f-9141-a95ae93a6c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voltar'])[1]/preceding::select[1]</value>
      <webElementGuid>8d5ff7fa-c850-4536-9db8-a6eaa8339e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'formularioDoisSabores', '&quot;', ')/table[1]/tbody[1]/tr[6]/td[2]/select[1]')])[1]/preceding::select[1]</value>
      <webElementGuid>165e0f65-4f90-48cf-828c-78a2c3909ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9b685ddd-8edd-4f88-ab96-8de137c33d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'quantidade' and (text() = '
        1
        2
        3
        4
        5
        6
        7
        8
        9
        10
    ' or . = '
        1
        2
        3
        4
        5
        6
        7
        8
        9
        10
    ')]</value>
      <webElementGuid>c1acf89a-5c97-4076-9b0e-deee4c09d7ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
