<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td</name>
   <tag></tag>
   <elementGuidId>d0904daf-2c0a-4634-bba1-908bc6a279d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tabelaCadastroTamanhosCardapio']/tbody/tr[2]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4f961b51-f093-476e-b406-273fb9c5ff8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabelaCadastroTamanhosCardapio&quot;)/tbody[1]/tr[2]/td[1]</value>
      <webElementGuid>2b8242d3-1c40-44fb-9ecf-f7de97778fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tabelaCadastroTamanhosCardapio']/tbody/tr[2]/td</value>
      <webElementGuid>0eb8ddaa-f354-423e-a753-c408c6a65441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preço de cada tamanho:'])[1]/following::td[1]</value>
      <webElementGuid>7184b114-0070-4207-812f-dd2b002b8045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tamanhos do Prato:'])[1]/following::td[2]</value>
      <webElementGuid>1b5ebe97-ad3d-46a6-914b-2935922a7103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R$'])[1]/preceding::td[1]</value>
      <webElementGuid>accfdcaf-c222-4407-b6a5-80600f18a491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R$'])[2]/preceding::td[3]</value>
      <webElementGuid>72146f85-a0de-4674-9bd7-97cffb2bce7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>c602b884-393e-497a-b799-6037c9baff67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
