<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DDD_dddTelCadastro</name>
   <tag></tag>
   <elementGuidId>aef4e620-57ea-4fec-a122-ef77617e87f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dddTelCadastroUsuario']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dddTelCadastroUsuario</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b1326b7-fc6e-443f-9351-18ee6e079b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dddTelCadastro</value>
      <webElementGuid>8335421e-a1bb-443f-85e1-65d95ee8adaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dddTelCadastroUsuario</value>
      <webElementGuid>7a9c9435-5e26-4465-9f78-90fe447ac834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18f5fb4b-a683-4fa2-be91-c210c32b6aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ae375dea-0723-463b-a0fb-2fbb5753cf4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cd8d67a9-7273-40b2-9024-98dce2278150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>$(this).mask('(00)')</value>
      <webElementGuid>fa51af54-5b57-4097-9c33-53882e452ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dddTelCadastroUsuario&quot;)</value>
      <webElementGuid>504ba4dd-0b83-412d-9edb-04e86c28150d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dddTelCadastroUsuario']</value>
      <webElementGuid>0ad50e24-ad83-4e40-b4b7-46b123c971cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div[3]/div/input</value>
      <webElementGuid>60000548-ebf5-4979-9d77-82cc1968bafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8acc7b01-d5f8-440c-a3f5-ea9fb3066b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dddTelCadastro' and @id = 'dddTelCadastroUsuario' and @type = 'text']</value>
      <webElementGuid>889dfefc-22e0-4ce3-83ae-279276566f9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
