<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bairro_bairroCadastro</name>
   <tag></tag>
   <elementGuidId>6dfef6f4-bd1c-42bb-9942-2f3f8447ec95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bairroCadastroEndereco']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bairroCadastroEndereco</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60802233-651c-42e9-a380-61c773a7adf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bairroCadastro</value>
      <webElementGuid>c8fe1274-b245-4a36-8091-8810d0f2647a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bairroCadastroEndereco</value>
      <webElementGuid>d7911d5c-cb5c-4a92-a75a-ee47af27bda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1f35d45-4b5c-4690-8604-f6738a28354b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>5fe8a02a-2df4-4b35-a4b7-be002333439a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c64c4988-dddc-4deb-934d-ebf10be54a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bairroCadastroEndereco&quot;)</value>
      <webElementGuid>d79492cc-ac41-46d4-8ed4-76171fc6efcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bairroCadastroEndereco']</value>
      <webElementGuid>9263f45c-bf6f-47b1-8c13-473bd8c7d38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div[8]/div/input</value>
      <webElementGuid>b19fc3d4-3219-4c8e-bb29-fe881d485c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>426d27bf-e490-4cbf-9d23-b42c1ce6746f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'bairroCadastro' and @id = 'bairroCadastroEndereco' and @type = 'text']</value>
      <webElementGuid>79e71915-2878-4beb-bbd3-2271a17226da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
