<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Complemento_complementoCadastro</name>
   <tag></tag>
   <elementGuidId>29ae594c-83d0-4a7b-8c99-44c119020545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='complementoCadastroEndereco']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#complementoCadastroEndereco</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c3efc21-ea7e-4a6c-9a3e-ac81cc6dd0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>complementoCadastro</value>
      <webElementGuid>7573f6eb-0d17-4889-9e1f-c291d87a2b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>complementoCadastroEndereco</value>
      <webElementGuid>b9618c39-2690-4304-8bb9-c07de3c00fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a44316f7-a1c6-4a25-ac1d-a0261fb0b89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>de76db55-0158-4649-90b5-d23bbeef8b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bef84441-638a-4585-818e-0e1111ef00a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;complementoCadastroEndereco&quot;)</value>
      <webElementGuid>77947603-aa69-43bb-920b-e3d6e668e206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='complementoCadastroEndereco']</value>
      <webElementGuid>ad79a4be-43b0-45b3-8cf1-859d1b94be5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div[8]/div[2]/input</value>
      <webElementGuid>a87922f2-eeec-454d-8c6d-07afec976c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/input</value>
      <webElementGuid>113059fb-04ce-49b7-a410-c5fe0c1fe396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'complementoCadastro' and @id = 'complementoCadastroEndereco' and @type = 'text']</value>
      <webElementGuid>6490407e-3c5f-484b-a3ba-72f520c39c7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
