<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nome_nomeCadastro</name>
   <tag></tag>
   <elementGuidId>dbef49e3-5e0f-4089-a734-d4ecce35e1d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nomeCadastroUsuario']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nomeCadastroUsuario</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0f55b22-8dc9-42f4-9ffc-243723311bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomeCadastro</value>
      <webElementGuid>44be41cf-8954-4f45-b80e-44446887a7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomeCadastroUsuario</value>
      <webElementGuid>ba0bd517-69ff-43a8-bbcd-0560e28ce69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4acd683-e54f-4019-ae3a-e90f56d4a112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>7a01335f-b822-4ef2-85d4-f53e82039c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7d912615-7a99-42d8-a2e9-c86e9d2fd688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomeCadastroUsuario&quot;)</value>
      <webElementGuid>c0531f7a-188d-429f-baa0-dd0902ae934e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nomeCadastroUsuario']</value>
      <webElementGuid>40ebadcf-84e9-4648-bd55-c56fe694ee39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div/div/input</value>
      <webElementGuid>94f922b5-34f3-4f41-9e04-5ef2904699c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c4feec85-a14c-4274-84d8-d4bf4a86eb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomeCadastro' and @id = 'nomeCadastroUsuario' and @type = 'text']</value>
      <webElementGuid>a413966a-dab6-447a-9854-a43780e5cb1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
