<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entrar_senha</name>
   <tag></tag>
   <elementGuidId>0ce6a39b-0915-4e3a-be51-c681e819342a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formSenhaUsuario</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'formSenhaUsuario']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formSenhaUsuario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>288c62d0-b805-4d6f-8acd-a56c26697e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7ccd69b2-470d-443c-8773-44c4322faa60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formSenhaUsuario</value>
      <webElementGuid>03b18db8-5ed2-4216-a3d5-40d1bbb7f61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bef69819-2236-47e4-a305-e4ecec08047a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Senha</value>
      <webElementGuid>1f744d41-41fc-4782-810a-373ab7302c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>senha</value>
      <webElementGuid>d371ba65-8205-4d75-a22e-4a4d8c5e7ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSenhaUsuario&quot;)</value>
      <webElementGuid>3420bea9-eb07-4138-9551-499788448d41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formSenhaUsuario']</value>
      <webElementGuid>371879b4-78ea-419b-ad27-94b2a0a52930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioLoginUsuario']/div[2]/input</value>
      <webElementGuid>27626cef-cf84-4947-ab5f-6fa8660784c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>476e63ed-8b65-45da-9a2f-0023ac1259ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'formSenhaUsuario' and @placeholder = 'Senha' and @name = 'senha']</value>
      <webElementGuid>b188bf4f-6827-4db4-ba55-0663b086e330</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
