<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entrar_login</name>
   <tag></tag>
   <elementGuidId>b3c268f8-d74d-4031-8ced-3144cea6c055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formLoginUsuario</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'formLoginUsuario']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formLoginUsuario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c28a4730-8248-4607-9ee0-ccc4cbe237da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7c53733-abf5-455c-9c44-30e0d35d5eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formLoginUsuario</value>
      <webElementGuid>1fa94231-1480-4dbd-98d7-1b71f3f64862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8350859a-d3cd-4dcd-8813-7c174ca7c310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Usuário</value>
      <webElementGuid>5527d9b2-8480-42d7-a296-1b16a4e079b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>6653ad52-d760-4888-8708-b9dbb4bc55ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formLoginUsuario&quot;)</value>
      <webElementGuid>f3cf2904-c6bc-4724-a1e3-4183b5c41b72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formLoginUsuario']</value>
      <webElementGuid>19b2aeed-6cd0-44b1-a7b9-a243ce97a12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioLoginUsuario']/div/input</value>
      <webElementGuid>87b4f137-8a6c-42ab-9959-467a060e79fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bbfcdd9c-d6ec-4d1c-8a94-e292aa3dd1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'formLoginUsuario' and @placeholder = 'Usuário' and @name = 'login']</value>
      <webElementGuid>374082e2-fcd3-479f-a7bd-ffb1c50c2694</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
