<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Entrar</name>
   <tag></tag>
   <elementGuidId>db326487-9bfd-4e51-9b6e-a70e09ae0c33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-outline-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Entrar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6f07723a-fc85-4c4d-aa5b-9eaa6bde824f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-success</value>
      <webElementGuid>3be6c0ad-82b1-4d1d-bc6a-242e5fc4d771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>login.php</value>
      <webElementGuid>fbf9313f-543d-49a8-8af6-7e63ae3cd78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entrar</value>
      <webElementGuid>f6f8dd30-3055-4efa-8bb6-03fa021c4960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;navbar navbar-expand-lg navbar-light bg-light&quot;]/a[@class=&quot;btn btn-outline-success&quot;]</value>
      <webElementGuid>be758a5e-c974-4130-8772-d949286599e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Entrar')]</value>
      <webElementGuid>f569f8cb-f326-4407-88f8-fcd72f134500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cadastre-se'])[1]/following::a[1]</value>
      <webElementGuid>c2bcff94-b3b0-420a-bc4c-b33c8ca9f812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Olá, visitante!'])[1]/following::a[2]</value>
      <webElementGuid>d9c29052-871c-4701-8e6f-9f67d9f5b4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restaurantes'])[1]/preceding::a[1]</value>
      <webElementGuid>45031fc2-6372-4556-9d27-cdff8982cf04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Papillon'])[1]/preceding::a[1]</value>
      <webElementGuid>d448d152-556d-431d-ba55-9b497c96fc97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entrar']/parent::*</value>
      <webElementGuid>73b7f621-1916-4e63-86d9-9ad08a61ee22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'login.php')]</value>
      <webElementGuid>531c012c-a59f-4508-ae8c-c7793f28550a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>ca966b96-8e7c-4ad1-8a71-ad1d44095e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'login.php' and (text() = 'Entrar' or . = 'Entrar')]</value>
      <webElementGuid>364156ad-3ce2-4fa6-8f66-0a143a758b0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
