<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entrar_senha</name>
   <tag></tag>
   <elementGuidId>339415ed-86b0-4ceb-96cc-93bfcdb36044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formSenhaUsuario</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formSenhaUsuario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14dd97c3-b026-410f-a451-1a2ff624a9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>aa4c759e-7c1c-4b5f-9ba4-4759087c7244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formSenhaUsuario</value>
      <webElementGuid>53156aee-46db-43ec-a778-9a2586f87590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>624f4235-3ae4-49d4-9297-29833a425219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Senha</value>
      <webElementGuid>32620aec-7a86-4179-a00f-f8e232cb7029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>senha</value>
      <webElementGuid>c7474747-4874-41b8-a67d-2c4211a08189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSenhaUsuario&quot;)</value>
      <webElementGuid>46c6a9c5-b8fa-4858-b623-75eb4da9e11a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formSenhaUsuario']</value>
      <webElementGuid>628d29f7-8fec-42a3-b3bd-dcff31784129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioLoginUsuario']/div[2]/input</value>
      <webElementGuid>53e692f5-0471-4c9b-b274-79bf60254068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4214796d-ec95-4fc1-871c-bb972469ab2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'formSenhaUsuario' and @placeholder = 'Senha' and @name = 'senha']</value>
      <webElementGuid>8ce78de2-717a-472c-a62e-f818abc3f560</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
