<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entrar_login</name>
   <tag></tag>
   <elementGuidId>3e73e9d3-7c56-4e78-ba51-8f6605b7be34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formLoginUsuario</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formLoginUsuario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e199e64b-5e91-4a05-a6b9-9cd2cf3b9b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b621af9-5c41-43c9-aa58-96b53bd18c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formLoginUsuario</value>
      <webElementGuid>f2ab238d-bf18-4b9a-aa8a-848415ed5a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9b7f04e2-7e4c-467a-bfbc-23d60c7be494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Usuário</value>
      <webElementGuid>35a662bb-c91c-431a-89c4-3fb51c84f2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>09a29413-a3f1-450f-b292-400ecc59d188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formLoginUsuario&quot;)</value>
      <webElementGuid>1c3d50cf-0c5d-45d6-96fb-055af70f4e0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formLoginUsuario']</value>
      <webElementGuid>b175817d-ea89-4dcb-8762-94c26a92a569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioLoginUsuario']/div/input</value>
      <webElementGuid>8542066d-7428-4127-9431-f183a5cdd553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1eedbed1-ecbb-4345-a202-d1b11485c234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'formLoginUsuario' and @placeholder = 'Usuário' and @name = 'login']</value>
      <webElementGuid>64f59c76-de64-447e-bb50-969c411c06ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
