<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mdia_tamanhos</name>
   <tag></tag>
   <elementGuidId>ea3ff70b-d25f-4690-aeb5-a5bbc0fe6fc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tamanhos[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tamanhos[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac0127d0-94c2-433f-9cdf-8088405826df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bb49e31b-5883-472c-b6f3-9a9964a0acd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tamanhos[]</value>
      <webElementGuid>fa2a6c79-983e-4933-bd81-9b160e5258b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>993d31cd-c879-4e72-864e-89a6a11fcbcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Calabresa</value>
      <webElementGuid>133e5e6b-4b81-48f9-a773-ed708cc6b023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formularioAdicionarCarrinho&quot;)/table[@id=&quot;tabelaCardapio&quot;]/tbody[1]/tr[3]/td[2]/div[@id=&quot;checkTamanhoPrato&quot;]/div[1]/input[1]</value>
      <webElementGuid>123c311c-106f-46cb-ba0b-4be8d7b607d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tamanhos[]']</value>
      <webElementGuid>054d1e8f-5935-45fa-9fbc-52cd27ccabb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkTamanhoPrato']/div/input</value>
      <webElementGuid>57f7aec1-25a7-4317-95bd-1b924b8714cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cd78a24e-f6ac-4096-9edf-3960d6b8b5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'tamanhos[]' and @title = 'Calabresa']</value>
      <webElementGuid>4ab433fc-7d2d-4b10-a10e-f44d4ecbd1fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
