<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_R 4,00_enviar</name>
   <tag></tag>
   <elementGuidId>c3bfe776-4372-4ae2-9d73-4b9bdfc60be1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='botaoSubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#botaoSubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8aaf06c6-a12e-4715-ae44-ba4afdbc103a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>botaoSubmit</value>
      <webElementGuid>b8e95e71-291e-4148-ad74-9d09c3073bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c430753c-a9e6-4ac1-979f-76a4d822e143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enviar</value>
      <webElementGuid>666cd436-bf73-40c7-ab7c-fa25ddcb2c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>1570f5d8-f5a9-4ecf-a11f-5bc1f21f8818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Adicionar ao Pedido</value>
      <webElementGuid>9bb0a06d-5927-4d66-a9a0-f8f91a1355a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;botaoSubmit&quot;)</value>
      <webElementGuid>02d94a08-8e6b-4e61-b070-2577ba349cdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='botaoSubmit']</value>
      <webElementGuid>674e963e-ea14-474e-a11c-cc340e0d339d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCalcularTotal']/input</value>
      <webElementGuid>96e3bcde-b908-4d62-83a4-0a0aff3ccc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7708125d-0bcd-4ae2-8175-1ce88d1c3e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'botaoSubmit' and @type = 'submit' and @name = 'enviar']</value>
      <webElementGuid>6427ea2a-9b1f-48eb-ac89-bdc3914d5336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
