<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Deletar</name>
   <tag></tag>
   <elementGuidId>6d2653cb-a0b7-44b0-97da-ae14782b0bc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Deletar' or . = 'Deletar')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr td:last-child</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Deletar')])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26056879-1664-4957-ba81-c6097f18808c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>cadastrarPizzaDoisSabores.php?restaurante=2&amp;deletarId=72</value>
      <webElementGuid>fa957bf6-5f20-4ab2-9608-d9f9c8651f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deletar</value>
      <webElementGuid>9bf75a9b-60ee-4f06-8fb4-b40ed9ca4c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/table[1]/tbody[1]/tr[9]/td[5]/a[1]</value>
      <webElementGuid>58da791f-085e-43d3-8fc7-7e0dbd372522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Deletar')])[8]</value>
      <webElementGuid>fdf0acbb-c7c4-47cd-bbe8-f7ccca83459b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R$ 15'])[2]/following::a[1]</value>
      <webElementGuid>7198a9dc-db22-4d13-afdf-a7f6c8220b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Média'])[2]/following::a[1]</value>
      <webElementGuid>92e582a2-cf52-4e0e-b633-69bf2a250947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/html[1]/body[1]/div[3]/table[1]/tbody[1]/tr[9]/td[5]/a[1]'])[1]/preceding::a[1]</value>
      <webElementGuid>1d297782-2e98-4ed2-8529-dafed3c225b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'cadastrarPizzaDoisSabores.php?restaurante=2&amp;deletarId=72')]</value>
      <webElementGuid>14697cab-689e-4ed7-8112-4bf7171dd834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[5]/a</value>
      <webElementGuid>1e4bcd32-6082-4076-9d6b-c5c6e73ef42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'cadastrarPizzaDoisSabores.php?restaurante=2&amp;deletarId=72' and (text() = 'Deletar' or . = 'Deletar')]</value>
      <webElementGuid>300e7ac8-8c02-4233-b410-97cd73d836d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
