<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mdia_tamanhos</name>
   <tag></tag>
   <elementGuidId>7888e0d9-9e69-4e93-8b72-2e829a81ca5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tamanhos[]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tamanhos[]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8abea167-7a50-46ed-8ee7-c26ae780d697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>732f0c6f-3d1b-4c86-8b10-eeeb6e7ce120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tamanhos[]</value>
      <webElementGuid>ba2abb21-6ef7-4e4c-82c7-86af41c316a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>7baa78a8-57e5-4e39-884b-c9680dd9be66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Chocolate</value>
      <webElementGuid>9d9379af-e329-423b-9755-07b7a0ee5ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;escolhaTamanhos&quot;)/form[1]/table[1]/tbody[1]/tr[1]/td[2]/div[@id=&quot;checkTamanhoPrato&quot;]/div[1]/input[1]</value>
      <webElementGuid>e3d074d2-0efb-4568-b0b2-f316bca41f5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tamanhos[]']</value>
      <webElementGuid>6689bc54-74ac-4482-9b95-8d293dc9b5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkTamanhoPrato']/div/input</value>
      <webElementGuid>2f903ff9-79fa-441c-84d5-5623f2e7edd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6fe2c167-861f-4813-ab92-586c03221783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'tamanhos[]' and @title = 'Chocolate']</value>
      <webElementGuid>ed4d866c-b125-48e8-9365-fce5fae9c423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
