<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mdia_tamanhos_1</name>
   <tag></tag>
   <elementGuidId>8c88d856-6f79-4bd9-b05d-f3d462fdf35c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td:nth-of-type(2) > #checkTamanhoPrato > #checkTamanhoPrato > div > input[name=&quot;tamanhos[]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='tamanhos[]'])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4219783e-d60e-433d-9e33-3d3a01fc96ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>acaf5aad-dd70-448d-91c1-cbec6844964f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tamanhos[]</value>
      <webElementGuid>351eec1d-db18-4c46-a6b8-61437ec5952a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>86961043-fd92-4055-a0fd-f1da95ff3847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Calabresa</value>
      <webElementGuid>0592497d-cf37-4d3a-b8cd-ce8dec95e419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;escolhaTamanhos&quot;)/form[1]/table[1]/tbody[1]/tr[4]/td[2]/div[@id=&quot;checkTamanhoPrato&quot;]/div[@id=&quot;checkTamanhoPrato&quot;]/div[1]/input[1]</value>
      <webElementGuid>0a609ac3-2172-4dc2-a145-5517906ba6e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='tamanhos[]'])[10]</value>
      <webElementGuid>544423af-1658-4dc9-9db7-0f11e8850e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='checkTamanhoPrato']/div/input)[10]</value>
      <webElementGuid>3e1e029d-49d9-4a22-afc4-3287076ebfc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/div[2]/div/input</value>
      <webElementGuid>ebafc811-df05-49b7-a514-672f832b9366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'tamanhos[]' and @title = 'Calabresa']</value>
      <webElementGuid>04d6ef3e-d57e-4228-8a5c-07f8712ba806</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
