<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_criarpizzadedoissabores</name>
   <tag></tag>
   <elementGuidId>2f261239-25ec-4b4d-b128-4615cb7d6bd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;submit&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@value = 'Criar pizza de dois sabores']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Avançar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa39ade2-ebd8-4106-8c3c-b8563adea830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>40881568-0d5d-4b6f-8caf-cb5601c9b339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Criar pizza de dois sabores</value>
      <webElementGuid>66bce7fc-3269-4004-8e0a-6311f7658a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;restaurantes&quot;)/form[1]/p[1]/input[1]</value>
      <webElementGuid>0bf40a36-b8b5-4b77-8557-030a9160b3bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Avançar']</value>
      <webElementGuid>6b6ba137-02d4-4780-9d57-b87284ec04bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='restaurantes']/form/p/input</value>
      <webElementGuid>c647f2c0-eb39-4a8a-b7a2-e55737cc5d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>28d65d2a-5ed9-4b23-a28e-61114fade28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>e089ea85-8f9f-4591-8cdd-327ad096b2d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
