<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Calabresa</name>
   <tag></tag>
   <elementGuidId>fa0a9385-e3ec-4fac-9022-16d007a9f743</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:last-child td:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Chocolate'])[3]/following::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b3f44a0b-5efc-451e-957c-d20075dccae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>5f72e230-71da-405c-b315-731a25465283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calabresa        </value>
      <webElementGuid>01f04ae8-56cb-4d13-b54c-88e7b3bd0e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/table[1]/tbody[1]/tr[9]/td[2]</value>
      <webElementGuid>cbe8ea6f-462f-4fac-8d4f-4eb123d1e8d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chocolate'])[3]/following::td[1]</value>
      <webElementGuid>5c16cd63-b5a5-4089-90ab-363764d098dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deletar'])[7]/following::td[2]</value>
      <webElementGuid>e6459b1a-c014-49fc-95e9-a527705acf61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Média'])[2]/preceding::td[1]</value>
      <webElementGuid>4554bc77-76a9-4d71-b2b7-39f7b1ca4c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R$ 15'])[2]/preceding::td[2]</value>
      <webElementGuid>d84b5ef4-697c-4bd9-81db-5808a0325932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]</value>
      <webElementGuid>ba616cb2-6bfe-48b3-a9c2-92bedd51e4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Calabresa        ' or . = 'Calabresa        ')]</value>
      <webElementGuid>cb3da414-4a20-41d0-be6e-8723c51a754f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
