<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Mdia</name>
   <tag></tag>
   <elementGuidId>694a1d59-21db-465b-94bc-1f879d73e8ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:last-child td:nth-child(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Calabresa'])[6]/following::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a043aef9-b0bc-48a2-b4ba-40ec9e2b7991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>a2740d2b-5bca-406c-a1bc-14226b29255a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Média        </value>
      <webElementGuid>a2ecabe0-4b7b-4c30-b7f4-db66c0bfc767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/table[1]/tbody[1]/tr[9]/td[3]</value>
      <webElementGuid>69f2b183-126c-49c5-a64a-80bd42a6a0d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calabresa'])[6]/following::td[1]</value>
      <webElementGuid>bd1d8bb0-730a-4d1f-8988-2a3d2c221319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chocolate'])[3]/following::td[2]</value>
      <webElementGuid>05cad315-59c0-49a5-a8b1-fdee30250cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R$ 15'])[2]/preceding::td[1]</value>
      <webElementGuid>909b4baf-005c-4308-a31e-de343a202c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deletar'])[8]/preceding::td[2]</value>
      <webElementGuid>b66ef36f-b25d-40ca-b337-f1a625e2013f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[3]</value>
      <webElementGuid>11c964d1-ec35-4fb0-9505-598906eae264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Média        ' or . = 'Média        ')]</value>
      <webElementGuid>5e52f3f9-8292-41fe-8886-9bc258e96505</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
