<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entrar_login (1)</name>
   <tag></tag>
   <elementGuidId>d5e56ff5-48e8-4a61-90c4-45decf8750d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formLoginUsuario</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formLoginUsuario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c7c2bbb-51a7-4290-81f7-4c8e7bb92560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cfc961d3-0652-401b-9a0a-3a1e53a46f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formLoginUsuario</value>
      <webElementGuid>b9cb619a-6496-4b4e-9482-040958eb68ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fa60ec62-e1a5-40dd-8ec1-727830cd4e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Usuário</value>
      <webElementGuid>62c7eee8-d313-4895-89b7-35be08a600d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>d1948ad0-0585-493e-86fe-6e6e6e4d0204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formLoginUsuario&quot;)</value>
      <webElementGuid>92c48182-0cdb-4669-aa6e-92e64cb6ca12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formLoginUsuario']</value>
      <webElementGuid>07aac210-ae33-4911-8d60-55016f70a264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioLoginUsuario']/div/input</value>
      <webElementGuid>43e01006-1ee8-4905-87b7-32a0b17514e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4f1d39b7-7415-43f9-8cf3-7095ba895309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'formLoginUsuario' and @placeholder = 'Usuário' and @name = 'login']</value>
      <webElementGuid>e45ffd81-9056-42ed-be30-2c6b60b8655b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
