<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entrar_senha</name>
   <tag></tag>
   <elementGuidId>3aa70c0f-24ed-46b3-a56b-626f4bda06ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formSenhaUsuario</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formSenhaUsuario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8693017-419e-42d2-b7fb-31cc92c5609d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7b1de508-268b-49f9-9590-9934ef9ded34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formSenhaUsuario</value>
      <webElementGuid>84339834-f83e-4eac-a41f-43bb2ea76e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>87528103-ad4c-49ba-a938-841a9a3971a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Senha</value>
      <webElementGuid>c8d713d1-2ef6-46cc-987c-be574b57f905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>senha</value>
      <webElementGuid>fd8f00e7-43d5-4765-ae75-0c18cbf40d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSenhaUsuario&quot;)</value>
      <webElementGuid>35d8ce42-311e-493f-8d92-25c844c64d4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formSenhaUsuario']</value>
      <webElementGuid>421c0b56-e76e-4b28-b974-c47a345636ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioLoginUsuario']/div[2]/input</value>
      <webElementGuid>70a45eef-9b37-4db7-95cf-9588dd50da63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>9d28cc6a-b9dc-4a27-a874-6ae2b7ae1622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'formSenhaUsuario' and @placeholder = 'Senha' and @name = 'senha']</value>
      <webElementGuid>4e0e0b0b-d0b3-4ddb-b6fa-edbc502f2363</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
