<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Entrar</name>
   <tag></tag>
   <elementGuidId>0056b533-1fe2-410f-9c2a-5c6485bb2103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-outline-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Entrar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>369df6d2-c231-4d9e-a9f0-1f7231344e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-success</value>
      <webElementGuid>04eeda68-b692-43ee-838e-9fe2b8dd3426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>login.php</value>
      <webElementGuid>a023cb4a-8c27-4caf-bae9-f993d003c2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entrar</value>
      <webElementGuid>a4395ae8-87d4-4c90-928f-ba9b2d505a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;navbar navbar-expand-lg navbar-light bg-light&quot;]/a[@class=&quot;btn btn-outline-success&quot;]</value>
      <webElementGuid>e45161c6-b15c-486e-9623-df15861b8ada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Entrar')]</value>
      <webElementGuid>f5aaac1d-fe96-484c-a877-57826215f2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cadastre-se'])[1]/following::a[1]</value>
      <webElementGuid>adc46243-4a21-46ef-a173-b5dc75dabe6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Olá, visitante!'])[1]/following::a[2]</value>
      <webElementGuid>c487ac64-313c-409c-b214-7d0722d3493f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restaurantes'])[1]/preceding::a[1]</value>
      <webElementGuid>44a2c8bd-3735-4620-b869-0fbd157c99d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Papillon'])[1]/preceding::a[1]</value>
      <webElementGuid>82b1e289-bbcd-4d4e-a5a0-7b8b7e2b0b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entrar']/parent::*</value>
      <webElementGuid>e866382e-7e99-4329-8582-7e39864f8bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'login.php')]</value>
      <webElementGuid>a8cb3fb6-e5f8-414e-88a9-585d8a70d1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>72ceedcc-03a2-41f2-8ef4-67d047db437b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'login.php' and (text() = 'Entrar' or . = 'Entrar')]</value>
      <webElementGuid>f677cd40-dbe3-4a62-898a-395964f18d8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
