<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_R 4,00_enviar</name>
   <tag></tag>
   <elementGuidId>b3e3858f-f695-48f2-afae-64d2e38f8588</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#botaoSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='botaoSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cea4d7d-0d79-49ce-91f7-1340708ec37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>botaoSubmit</value>
      <webElementGuid>8a89cc83-e9db-4d5d-9969-e0d3559c7b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b8ea90ed-4024-4706-8562-c8233c4144dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enviar</value>
      <webElementGuid>08941ed5-354f-4c66-902a-4fe80f22b595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>d276a377-7f98-4e19-863f-17e285604a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Adicionar ao Pedido</value>
      <webElementGuid>dd414c72-6471-4313-ba99-88c0cfbd7dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;botaoSubmit&quot;)</value>
      <webElementGuid>09ab4e73-0200-4436-9b03-a719c0db086b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='botaoSubmit']</value>
      <webElementGuid>2dedc1a3-8040-446f-95e3-8244cff31ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCalcularTotal']/input</value>
      <webElementGuid>47423cf2-4ea2-4328-992b-9175b2e154be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0e9f343f-fe27-4a19-b5a7-90f03efd6060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'botaoSubmit' and @type = 'submit' and @name = 'enviar']</value>
      <webElementGuid>84df8000-b6e0-4ea3-ae73-c0959be7ad3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
