<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1             2            3        _cee02f</name>
   <tag></tag>
   <elementGuidId>fc2d698c-21ac-4eb9-a478-7e5c4c08707e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;quantidade28&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='quantidade28']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>34b325d4-74b9-49e0-9e8e-4ac926411549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantidade28</value>
      <webElementGuid>14ea2bd9-2f8a-45b2-bcf1-a2e0877d45ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        	1 
            2
            3
            4
            5
            6
            7
            8
            9
            10
        </value>
      <webElementGuid>00d5725c-8ed3-430f-8fa7-2d475e608a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formularioAdicionarCarrinho&quot;)/table[@id=&quot;tabelaCardapio&quot;]/tbody[1]/tr[7]/td[3]/div[@id=&quot;quantidade&quot;]/div[1]/select[1]</value>
      <webElementGuid>4d98ae8a-2bd5-47cb-a020-d3b073254ed1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='quantidade28']</value>
      <webElementGuid>9ae48c01-7434-4feb-8125-59ed55d9fc5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='quantidade']/div/select)[13]</value>
      <webElementGuid>88a0166c-c89d-43c9-8c5f-12e604882a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Montar pizza com dois sabores'])[1]/preceding::select[2]</value>
      <webElementGuid>06d73a35-f2ca-4a69-91d1-2fb1fe9997a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bebida'])[1]/preceding::select[2]</value>
      <webElementGuid>b05ab045-c9bc-40d4-aeba-e018e52c84b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[3]/div[2]/div/select</value>
      <webElementGuid>ee8245d7-e5f7-40ad-a724-8f99688dcfa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'quantidade28' and (text() = '
        	1 
            2
            3
            4
            5
            6
            7
            8
            9
            10
        ' or . = '
        	1 
            2
            3
            4
            5
            6
            7
            8
            9
            10
        ')]</value>
      <webElementGuid>0c664bc7-219c-4efa-87b2-0ffe5563c985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
