<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_finalizar_pedido</name>
   <tag></tag>
   <elementGuidId>5ea89a28-6efd-43df-beea-15c7d11445b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;tabelaResumoPedidoRestaurante&quot;)/tbody[1]/tr[8]/td[1]/form[1]/p[1]/input[@class=&quot;btn btn-success&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='formaEntrega']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;formaEntrega&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>445d8da4-bc0c-4b5f-be2d-f7a17b208398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>a0f81714-7cc3-4319-8d23-e4d934f492c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>fd2ca293-5e85-4e67-b0b0-f60c4aad8173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>6961994a-9428-4a58-8412-4945f34b30c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioFormaEntrega&quot;)/input[1]</value>
      <webElementGuid>42bb4100-c207-42f4-9854-5ffee2f51534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formaEntrega</value>
      <webElementGuid>3c4804ce-8fd3-4db9-810b-6e1db24c4c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b68a3ed1-fcad-4dce-a189-1af0e68935dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='formaEntrega']</value>
      <webElementGuid>ed49d515-8c12-48e3-8a91-7a859966df72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radioFormaEntrega']/input</value>
      <webElementGuid>cf52af1f-b22b-401b-bc1c-9b08b6456a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7d8a470c-d188-4a22-a0cd-4cb50cc335a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'formaEntrega']</value>
      <webElementGuid>2a451206-ccff-4328-a2b9-b2b67764f1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Finalizar Pedido!']</value>
      <webElementGuid>ca9107d0-8ce4-47a4-86c0-12464078ddf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tabelaResumoPedidoRestaurante']/tbody/tr[8]/td/form/p/input</value>
      <webElementGuid>b3e1f4d7-5345-4a69-8fad-053829e56cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/p/input</value>
      <webElementGuid>4a56bc3b-a081-4e15-b5f6-c538d765b904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>04a9020a-4a45-4d0d-ac8f-255df537d032</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
