<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bairro_bairroCadastro</name>
   <tag></tag>
   <elementGuidId>6dfef6f4-bd1c-42bb-9942-2f3f8447ec95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bairroCadastroEndereco']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bairroCadastroEndereco</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b7e6bc2-6745-42c3-ba2d-fa3b0abd043f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bairroCadastro</value>
      <webElementGuid>abde9e40-72d7-469a-a517-8d1e71d098bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bairroCadastroEndereco</value>
      <webElementGuid>e79298ad-11e4-4a19-8bcf-06c732804035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>263cf54b-33a0-48ab-a140-f590c0e09f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f74837d6-3f3d-479c-ba2c-e19ac1abeadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9b7f2ab2-5fd3-4c31-bca4-fa65a631d307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bairroCadastroEndereco&quot;)</value>
      <webElementGuid>70857aee-5567-4680-ad22-b9658b0ad001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bairroCadastroEndereco']</value>
      <webElementGuid>965d22c8-eaa4-4ed4-be63-12b25fecd2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div[8]/div/input</value>
      <webElementGuid>eec2018d-837c-4f97-8d67-1bb507b2eb50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>2a9262d7-14ff-4e88-a405-839c26a92fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'bairroCadastro' and @id = 'bairroCadastroEndereco' and @type = 'text']</value>
      <webElementGuid>93ef87f3-4e8a-424e-93f3-03054342b787</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
