<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Complemento_complementoCadastro</name>
   <tag></tag>
   <elementGuidId>29ae594c-83d0-4a7b-8c99-44c119020545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='complementoCadastroEndereco']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#complementoCadastroEndereco</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3ce8db0-c803-4abe-9803-e64379edd6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>complementoCadastro</value>
      <webElementGuid>b9bbfb2d-d608-4ae0-a78c-77e79d06484d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>complementoCadastroEndereco</value>
      <webElementGuid>fe914cf1-6f71-4cbd-bd51-fe1d324f193d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aeff063d-3d05-4125-a7ed-74ed96f66296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b04b79df-52af-4216-8bad-7a3963f27aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>993ab7bb-544e-4114-a6b2-e1b2904a0a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;complementoCadastroEndereco&quot;)</value>
      <webElementGuid>6f00887f-cf07-4ed5-86ce-c9ad5536b71e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='complementoCadastroEndereco']</value>
      <webElementGuid>03000fdb-fffa-4310-b3de-1f0629d8e598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div[8]/div[2]/input</value>
      <webElementGuid>73119051-2255-4509-ba7e-07c74d6dace9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/input</value>
      <webElementGuid>c16b4f5e-3942-4f56-9e74-6c3d8ae699c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'complementoCadastro' and @id = 'complementoCadastroEndereco' and @type = 'text']</value>
      <webElementGuid>94394f23-0f1a-4d75-ad27-86047fa28c03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
