<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cidade_cidadeCadastro</name>
   <tag></tag>
   <elementGuidId>78f1f8fc-ee60-48f3-9725-388fa7ad73ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cidadeCadastroEndereco']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cidadeCadastroEndereco</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d228ecf9-3a32-45e0-b344-95a61714185d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cidadeCadastro</value>
      <webElementGuid>a18720e2-110e-4df4-add0-38643fe1860d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cidadeCadastroEndereco</value>
      <webElementGuid>bae9d3b1-0ee7-478d-b575-f9898848d0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aef9225a-5eb2-42b1-b62c-ac338f450d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>645b05ca-e854-4f5f-a313-c8ea32f73226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>628f6c48-5ece-4033-b8b4-2e5962913c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cidadeCadastroEndereco&quot;)</value>
      <webElementGuid>e7489cb0-6241-4b85-bdbe-c9f425eacdae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cidadeCadastroEndereco']</value>
      <webElementGuid>33dc220c-5b30-447b-8882-6d267b92e1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div[9]/div/input</value>
      <webElementGuid>154e8860-e7c9-43f6-b658-502670fee677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>79ab50bf-73ce-44e9-816f-5a8338f0a888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cidadeCadastro' and @id = 'cidadeCadastroEndereco' and @type = 'text']</value>
      <webElementGuid>d2368b96-c32b-4af9-a80b-84b6895de536</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
