<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DDD_dddTelCadastro</name>
   <tag></tag>
   <elementGuidId>aef4e620-57ea-4fec-a122-ef77617e87f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dddTelCadastroUsuario']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dddTelCadastroUsuario</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>083f5cff-d7c8-44a4-a130-1ef3ccddc7b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dddTelCadastro</value>
      <webElementGuid>edbe39d0-ef3a-491d-94f1-aa8d64394ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dddTelCadastroUsuario</value>
      <webElementGuid>af6b31c2-c906-434f-9f6e-a6b913a254ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f5e8dc2-73b2-4e6a-a20f-baa1083b390e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>49a8148b-6937-46ad-b6e6-7f78c31eebb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c037d72c-2975-4b42-b967-c027021b8c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>$(this).mask('(00)')</value>
      <webElementGuid>82ad5c7b-1ab6-4a53-a8e1-c63c579aa016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dddTelCadastroUsuario&quot;)</value>
      <webElementGuid>b7ba8408-411d-4a9b-978f-d570fd4b3086</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dddTelCadastroUsuario']</value>
      <webElementGuid>b73b9402-6836-4e53-9149-89ff0f76f678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div[3]/div/input</value>
      <webElementGuid>0143a7d8-a0cf-4cf8-9a9b-90e904a10c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>a47402af-32f8-48dd-8b14-3c31184d3be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dddTelCadastro' and @id = 'dddTelCadastroUsuario' and @type = 'text']</value>
      <webElementGuid>f18b4588-e733-4ba5-abfa-c2c71796596d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
