<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ALAPAMBACEDFESGOMAMTMSMGPAPBPRPEPIRR_4d941d</name>
   <tag></tag>
   <elementGuidId>d3fe96f6-2e29-491d-99af-4bc7e53b56d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='estadoCadastro']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;estadoCadastro&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bdb05267-403b-4807-883f-3a8ebf05aa97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>estadoCadastro</value>
      <webElementGuid>581c402a-2379-4d2f-8022-8ea225afe12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uf form-control</value>
      <webElementGuid>eab6c726-ca5f-4914-b712-3d1114eab95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
											AL
											AP									
											AM									
											BA									
											CE									
											DF									
											ES									
											GO									
											MA									
											MT									
											MS									
											MG									
											PA									
											PB									
											PR									
											PE									
											PI									
											RR									
											RO									
											RJ									
											RN									
											RS									
											SC									
											SP									
											SE									
											TO	
										</value>
      <webElementGuid>6a84b9a4-ac47-46c2-8bf3-be74265be10b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formularioCadastroUsuario&quot;)/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group col-md-6&quot;]/select[@class=&quot;uf form-control&quot;]</value>
      <webElementGuid>6fc69e28-ea44-4d2e-a1ab-c459c5d7a53f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='estadoCadastro']</value>
      <webElementGuid>f7a013fb-f14f-4fde-ac93-47d87681fae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroUsuario']/div[9]/div[2]/select</value>
      <webElementGuid>af6a3f24-272e-43c8-820f-2a02bdf766f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UF'])[1]/following::select[1]</value>
      <webElementGuid>91586a0b-f035-4b05-b550-c390e0bfff3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cidade'])[1]/following::select[1]</value>
      <webElementGuid>0f2198f2-d48a-4971-9055-de70610ff7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cadastrar'])[1]/preceding::select[1]</value>
      <webElementGuid>38e2b8cc-5d7a-4981-a1d2-9ff33d8a2dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7470ec8b-9782-48f2-9331-c72dfb599dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'estadoCadastro' and (text() = '
											AL
											AP									
											AM									
											BA									
											CE									
											DF									
											ES									
											GO									
											MA									
											MT									
											MS									
											MG									
											PA									
											PB									
											PR									
											PE									
											PI									
											RR									
											RO									
											RJ									
											RN									
											RS									
											SC									
											SP									
											SE									
											TO	
										' or . = '
											AL
											AP									
											AM									
											BA									
											CE									
											DF									
											ES									
											GO									
											MA									
											MT									
											MS									
											MG									
											PA									
											PB									
											PR									
											PE									
											PI									
											RR									
											RO									
											RJ									
											RN									
											RS									
											SC									
											SP									
											SE									
											TO	
										')]</value>
      <webElementGuid>d80a60e2-45a9-49c9-bead-a7e62abe7cb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
