<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_R 27,00</name>
   <tag></tag>
   <elementGuidId>10ee3666-07df-4216-bad4-3237fe021276</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='valorTotalPedidoRestaurante']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#valorTotalPedidoRestaurante</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>faa32510-8e13-4f11-9d6d-93c5493d2094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>valorTotalPedidoRestaurante</value>
      <webElementGuid>526267bb-b57d-4be0-b74a-5f3c42f67516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>ce9dd382-7261-48f4-aa50-8abe110d5abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> R$ 27,00 </value>
      <webElementGuid>7350bbd0-0470-4656-92b5-f4bfde7c2d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;valorTotalPedidoRestaurante&quot;)</value>
      <webElementGuid>8a54440a-2b69-491a-ac3c-8c63f6195bdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='valorTotalPedidoRestaurante']</value>
      <webElementGuid>c685d4a5-806f-427a-a618-5497aa66d755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tabelaResumoPedidoRestaurante']/tbody/tr[7]/td[2]/h2</value>
      <webElementGuid>cd0bc3c4-c461-45b6-9f33-d3686a7ff700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total do pedido'])[1]/following::h2[1]</value>
      <webElementGuid>989ebce5-3488-4a05-a8be-a9909e4186e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R$ 0,00'])[1]/following::h2[2]</value>
      <webElementGuid>519c86e2-3d7e-4ac5-bf11-8c11871bc851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formas de Pagamento'])[1]/preceding::h2[1]</value>
      <webElementGuid>d4674159-d901-4495-95a2-dc664c70482d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/h2</value>
      <webElementGuid>688dabff-20b8-41c1-8a69-ca329152c22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'valorTotalPedidoRestaurante' and (text() = ' R$ 27,00 ' or . = ' R$ 27,00 ')]</value>
      <webElementGuid>6f893f11-22ba-40fd-afbb-1fe9765da0df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
