<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nome da Categoria_nomeCategoria</name>
   <tag></tag>
   <elementGuidId>b6ae346a-d584-42d0-ac1a-e9196b26715f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nomeCategoria</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nomeCategoria']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c0f36e8-aa2f-4887-be0e-02f6cd1a6477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomeCategoria</value>
      <webElementGuid>060b0213-3964-4110-a720-061ecd356418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomeCategoria</value>
      <webElementGuid>a5fec64e-9da0-4460-ad55-450bac75e1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55c9fd11-e69a-44b2-8b71-510ee1893dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>f0bafdb4-acd8-482d-9241-535fc293460e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomeCategoria&quot;)</value>
      <webElementGuid>6a2be1f2-b7f9-4299-aafb-6372f8c99450</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nomeCategoria']</value>
      <webElementGuid>c4b354b5-0706-4880-9d8c-3f6b05f7ab3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divNomeCategoriaFormulario']/p/input</value>
      <webElementGuid>c160db17-7407-41e1-8e40-8fd1679e0fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b8c5d6ef-3e18-4af4-9c22-007e9f99a792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomeCategoria' and @id = 'nomeCategoria' and @type = 'text']</value>
      <webElementGuid>5094dce5-7ce7-4b4d-b157-a4c436802b49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
