<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Horrio de Funcionamento_horaFim (1)</name>
   <tag></tag>
   <elementGuidId>4477797b-9de0-40f4-9950-039871c551b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#horaFimRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='horaFimRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>156e2bb0-c1c9-4e9d-847c-55b225050b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>horaFim</value>
      <webElementGuid>f4464d06-0ba6-4954-9cdd-bd35143e5c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>horaFimRestaurante</value>
      <webElementGuid>f9b96126-c374-4bf7-a1f1-d5abc0f62223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73db4645-227c-4ff5-81c0-e80d3c324e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>70b8be46-d646-465d-aabe-b31c84b4f37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>1d313958-d049-4115-a2f5-1e838c56353a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>00:00:00</value>
      <webElementGuid>e84b8777-02eb-4e91-afa5-54d0917dbebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;horaFimRestaurante&quot;)</value>
      <webElementGuid>13012c0b-ec7a-4e2e-bab8-418cc5a26efb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='horaFimRestaurante']</value>
      <webElementGuid>9352e51a-ca4c-4658-87b7-b27c9d9cc745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[6]/input[2]</value>
      <webElementGuid>4a9703b6-4253-4585-a961-32d202f89ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input[2]</value>
      <webElementGuid>a888ad49-fb34-4c13-9556-4f9344eb72ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'horaFim' and @id = 'horaFimRestaurante' and @type = 'text']</value>
      <webElementGuid>8ee47da8-a777-4685-89fc-ccf72d3fa44b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
