<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cidade_cidadeCadastro (1)</name>
   <tag></tag>
   <elementGuidId>df7a4f37-456e-474d-8cf4-1a9d821185c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cidadeCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cidadeCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f1a2d83-71ee-4d2a-9acb-c9ce9bb9a99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cidadeCadastro</value>
      <webElementGuid>19d3934a-af5c-4532-9517-325520043bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cidadeCadastroRestaurante</value>
      <webElementGuid>8ede4f67-45ec-4f27-b994-9a4666c124c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43424bda-9489-41c5-b2e4-2cef42d1220a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>d74f22c9-8496-4253-9b28-175067f54a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cidadeCadastroRestaurante&quot;)</value>
      <webElementGuid>0b97ae79-6605-4b60-87fc-5d05e1c257d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cidadeCadastroRestaurante']</value>
      <webElementGuid>1a31f9fd-45fe-4e64-851f-b8efa5e568a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[4]/input</value>
      <webElementGuid>ecf2155a-c2dc-4077-b816-027a18fcb735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>5e6dd97f-5295-44c2-a5ef-288745f64db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cidadeCadastro' and @id = 'cidadeCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>16a449fb-2627-45d8-b9a4-59253fc8b619</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
