<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cidade_cidadeCadastro</name>
   <tag></tag>
   <elementGuidId>bd73cc46-f350-4db6-a908-ba38d68e649d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cidadeCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cidadeCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e05cba42-7ee3-4ce4-b177-2f9ed1fa4fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cidadeCadastro</value>
      <webElementGuid>00a39818-2066-45ee-87b7-59aadf4b7901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cidadeCadastroRestaurante</value>
      <webElementGuid>0aa959a3-60d1-4c7c-b7f6-6a937354d5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef714087-28eb-4776-af13-919059bf84cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>077cf3b3-87d4-4492-8393-91d7acf47cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cidadeCadastroRestaurante&quot;)</value>
      <webElementGuid>dd412463-5fe2-4de9-8d62-37e4963a45d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cidadeCadastroRestaurante']</value>
      <webElementGuid>1fb71e74-cb32-4e92-995a-09ce980786cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[4]/input</value>
      <webElementGuid>676b1531-8a82-4d90-af97-9685b38f24b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>8343ae20-5b0a-4fb3-9b6b-f4f803411087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cidadeCadastro' and @id = 'cidadeCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>5d0c8888-4fab-46e3-8cc4-10fb8f5231d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
