<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Complemento_complementoCadastro (1)</name>
   <tag></tag>
   <elementGuidId>68cb3393-ea1e-4ba8-9e1e-ca48b0900c45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#complementoCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='complementoCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b927b5e9-731d-4485-ae91-6fa32b80848f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>complementoCadastro</value>
      <webElementGuid>5d1485a0-32c8-4902-a5d3-44f9d59e486b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>complementoCadastroRestaurante</value>
      <webElementGuid>5702a323-2dc0-47e5-8187-b8f348e8cca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e75dbc4-559e-4d21-9d9b-3d5ffd651dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f3ee846c-9a11-44ba-ab3e-64959a7a2c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;complementoCadastroRestaurante&quot;)</value>
      <webElementGuid>f5cc4ae3-74e5-4e97-975e-bcc4c1629bd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='complementoCadastroRestaurante']</value>
      <webElementGuid>6a77f0a6-7651-4d6e-9cf2-4d4185645337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[3]/input[2]</value>
      <webElementGuid>ae629188-ac13-4a05-b545-d27835cb4d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>a82bbf98-1e76-4cbd-af8b-e3e59e697c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'complementoCadastro' and @id = 'complementoCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>2c098be8-4dbc-4273-895c-7f500e8646a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
