<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Horrio de Funcionamento_horaFim</name>
   <tag></tag>
   <elementGuidId>e1184c24-3725-4a82-bbce-3b318ae7a10a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#horaFimRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='horaFimRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>556de0ee-b03a-4627-8b9f-6828b6186504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>horaFim</value>
      <webElementGuid>cab0cd7e-52b3-4040-a39f-2c781aa0b6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>horaFimRestaurante</value>
      <webElementGuid>53821a79-39b0-4bfc-a22a-5b2c6fb24cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2bee06b1-7f36-4772-a2f3-c26d49cbd018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>3b18a6d0-a4f8-4b0d-9f6f-bce399d9842f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>ae1c6015-2659-48b3-9a52-ab915f1c6502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>00:00:00</value>
      <webElementGuid>6a2171ca-17e7-4efe-a19b-0dd80a2cc358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;horaFimRestaurante&quot;)</value>
      <webElementGuid>8e4c8fd8-3040-40de-9530-b927894bb866</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='horaFimRestaurante']</value>
      <webElementGuid>da853bb9-7456-402c-89a9-a3a07eac7596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[6]/input[2]</value>
      <webElementGuid>cdde13a4-85e8-41d4-b93a-243d14c46dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input[2]</value>
      <webElementGuid>1c46d62f-dcd9-48ef-acf8-b750e8f2a71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'horaFim' and @id = 'horaFimRestaurante' and @type = 'text']</value>
      <webElementGuid>bf6b8182-0476-4eab-93a4-289e5ed68875</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
