<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RuaAv_ruaCadastro (1)</name>
   <tag></tag>
   <elementGuidId>112e6646-3748-4b39-8212-ee437532f05b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ruaCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ruaCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0faf0e9-faed-4e53-aa5c-e8caa70f415a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ruaCadastro</value>
      <webElementGuid>851b813e-c611-4db9-9b20-091b8920848e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ruaCadastroRestaurante</value>
      <webElementGuid>809f304e-1f6a-4819-962c-3b3bf50a4545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44b84b10-37c7-4382-8bad-a08925f54a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>08af1512-f66a-4890-aced-2858d34501c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ruaCadastroRestaurante&quot;)</value>
      <webElementGuid>c89c0580-4db0-47b1-8eef-d8480c32a7a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ruaCadastroRestaurante']</value>
      <webElementGuid>e2feb071-70a4-4dcb-95da-c85118cf623a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[2]/input</value>
      <webElementGuid>039cb813-37ed-4131-b948-394e31cd791d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>bd1ea667-20e9-4370-979e-e2c3c82a8720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ruaCadastro' and @id = 'ruaCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>beb85779-8ec9-43a8-aec2-9c73a3a5fec7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
