<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telefone_telCadastro</name>
   <tag></tag>
   <elementGuidId>dafc96a1-e36b-46de-a8e5-147c7198421d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#telCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='telCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97248155-01de-4f9d-9735-32f56bac3b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>telCadastro</value>
      <webElementGuid>901659a3-4ef2-4945-a01b-75a8464b4003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telCadastroRestaurante</value>
      <webElementGuid>736edfe1-dd94-4e67-a582-9615fd4c71bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8f688b1-2721-4957-9c2c-9e3fa5d4ab65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>eb09aa49-c7b1-48aa-8348-0a54f590cb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telCadastroRestaurante&quot;)</value>
      <webElementGuid>954f431f-c3c1-4104-9562-e22c1c50eaf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='telCadastroRestaurante']</value>
      <webElementGuid>a882268e-f1df-433c-b511-781dc224f14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[5]/input[2]</value>
      <webElementGuid>01720b45-53e0-4d00-affb-898b54f35003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input[2]</value>
      <webElementGuid>52878375-aaae-4417-9f15-504e8381a4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'telCadastro' and @id = 'telCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>ee5807ff-d3c6-4133-86f5-d2331de36bda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
