<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nome_nomeCadastro</name>
   <tag></tag>
   <elementGuidId>0ce444fc-6332-4b86-90e5-68ed0e66f67a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nomeCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nomeCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1da2a61c-49e7-4c66-b1b0-74a1443d196a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomeCadastro</value>
      <webElementGuid>de81c787-68cc-4976-9133-f865f9618b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomeCadastroRestaurante</value>
      <webElementGuid>a943da58-8869-4c0e-816c-b8ff6e7fa9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0484c56a-475c-4a0c-9018-0ee15c61bb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>e7816db5-dc16-4ca8-bc9b-85bd784bd1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomeCadastroRestaurante&quot;)</value>
      <webElementGuid>76696824-902c-4806-bfd3-ca2c155cf08e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nomeCadastroRestaurante']</value>
      <webElementGuid>bf4e4989-1540-486c-9fcd-b36a5ae9de8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div/input</value>
      <webElementGuid>b922e69d-559d-48e8-b0bd-5b2273bda407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fe67b5a4-7089-453a-acef-aa077ccde1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomeCadastro' and @id = 'nomeCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>fa90e64e-28b4-4124-8d66-607c595df66c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
