<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telefone_telCadastro (1)</name>
   <tag></tag>
   <elementGuidId>6a34ac0d-02f1-4816-81f9-965a769a64a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#telCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='telCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8908d593-f426-4727-9833-f9fa70e68a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>telCadastro</value>
      <webElementGuid>1d1324a7-fc28-4c13-a527-2240f5b72009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telCadastroRestaurante</value>
      <webElementGuid>3e1a1cc5-a365-4dc3-87a6-6a6fd7c21d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fef3e0e8-0b9d-4791-b094-da1a6e7004bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>082fa827-683c-485c-9932-861bcea8a67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telCadastroRestaurante&quot;)</value>
      <webElementGuid>23416e76-6de0-43a3-8894-1ba299369b8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='telCadastroRestaurante']</value>
      <webElementGuid>a9c91323-bd44-44fb-b0d9-a127d003215e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[5]/input[2]</value>
      <webElementGuid>4fd1cf88-c68e-49d2-b4da-3b48b4268b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input[2]</value>
      <webElementGuid>a0f305b7-22e1-49b3-856c-2b2318d096c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'telCadastro' and @id = 'telCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>a2e7c943-eec9-4219-9143-adba792a32ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
