<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telefone_dddTelCadastro (1)</name>
   <tag></tag>
   <elementGuidId>f51eab8c-1f9d-452d-bebd-318b17c06e84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dddTelCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dddTelCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cda93ee-44d0-4044-a9d9-fb50905cb261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dddTelCadastro</value>
      <webElementGuid>c6faf2cf-5162-4439-88ec-bbbd6672026a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dddTelCadastroRestaurante</value>
      <webElementGuid>d14bd61b-951d-41bd-8a85-8571f4fe691b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>363442dc-df08-4c44-82d4-0c9151264b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6dcca661-f639-49f1-9741-5102ad522e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dddTelCadastroRestaurante&quot;)</value>
      <webElementGuid>9392c785-c91c-48c1-8844-db0056af26ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dddTelCadastroRestaurante']</value>
      <webElementGuid>754099a0-2d65-49b1-a2cd-3d51f1a4594e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[5]/input</value>
      <webElementGuid>80b93d2c-6f3f-49f9-9b1e-37c7631a8488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>83985e19-3625-4e1b-ac54-9143b5753659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dddTelCadastro' and @id = 'dddTelCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>4f6df9e3-c16d-4b98-816a-e51bf3a9e080</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
