<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero_numeroCadastro (1)</name>
   <tag></tag>
   <elementGuidId>f634ec40-3799-4f77-aaab-2724905778e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numeroCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numeroCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca5cfe60-a6a5-4ad7-ae26-9cb50f3ed5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numeroCadastro</value>
      <webElementGuid>153ccc65-0635-4260-ab1e-cdb1c0945cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numeroCadastroRestaurante</value>
      <webElementGuid>a2e33080-b30e-4726-97a2-47e6e19649ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff8c7305-1951-4ba6-8884-575bd490dd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>eac48624-d4d8-44ed-a1be-63fe34373758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numeroCadastroRestaurante&quot;)</value>
      <webElementGuid>87a5a7cd-3969-47f6-8aba-8f2ed546743a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numeroCadastroRestaurante']</value>
      <webElementGuid>3ddfb1a7-98c4-4c80-b5c7-3e4859b6213c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[3]/input</value>
      <webElementGuid>5cffbcc2-b8bc-4b73-8244-785ffa5907b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>78569b11-ec2d-4a97-b4dc-eb9143ccad73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'numeroCadastro' and @id = 'numeroCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>0eb6b07f-f00b-4110-a39c-6fb0b9881ce1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
