<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Horrio de Funcionamento_horaInicio (1)</name>
   <tag></tag>
   <elementGuidId>0ee9f6d6-09e4-4a18-aea1-2403e5c239e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#horaInicioRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='horaInicioRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b737b0a-1d94-4556-9a16-6cf3dc33799f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>horaInicio</value>
      <webElementGuid>c332c04e-26c0-4731-9ade-2229c65b7dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>horaInicioRestaurante</value>
      <webElementGuid>4cd72209-7b33-4a4f-838f-c60831594fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b88198f8-f9a4-41d7-99be-5214f950530a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>1c37370b-ef48-4b8b-a485-fc0486e60cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>5274f6f3-63f3-415d-abfd-825da57f0bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>00:00:00</value>
      <webElementGuid>26dcd712-ab57-48a6-a7a1-3dce8a3a7729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;horaInicioRestaurante&quot;)</value>
      <webElementGuid>eb395202-a3ca-473e-bb6b-b3cb6d7e1125</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='horaInicioRestaurante']</value>
      <webElementGuid>fd9ad874-a25c-4b6f-857d-4fd79795caf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[6]/input</value>
      <webElementGuid>80d5735f-d3f2-4b6d-872e-b26ced3ac44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>3ad2aac9-b76f-48b3-8fb8-04aaa3cf913d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'horaInicio' and @id = 'horaInicioRestaurante' and @type = 'text']</value>
      <webElementGuid>9b1270ff-bb06-4946-8708-66cdeb3355d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
