<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bairro_bairroCadastro (1)</name>
   <tag></tag>
   <elementGuidId>aca4d139-9cdc-4cea-9c8b-db0625622498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bairroCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bairroCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23d840a4-f9e3-4022-8dd7-956c01bdb3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bairroCadastro</value>
      <webElementGuid>61ed6876-401c-40e9-aa30-80db459a1190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bairroCadastroRestaurante</value>
      <webElementGuid>caa6c6cf-3d8a-4da4-a6ba-cb43eff808bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7af798aa-4b81-4bca-be7e-f6cd9a905c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>01fc2225-93fe-4ae0-a402-c0d52b54d7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bairroCadastroRestaurante&quot;)</value>
      <webElementGuid>709ed5a8-a7e2-465a-977f-8bb07a71ba49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bairroCadastroRestaurante']</value>
      <webElementGuid>a47317fd-ee11-415e-9ece-4fc9bd2ad199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[3]/input[3]</value>
      <webElementGuid>5060535c-4d5a-4409-854c-1c5b5bc1260a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>980e29aa-f466-419b-8772-08d66e2517f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'bairroCadastro' and @id = 'bairroCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>426a375f-d7d6-4c49-ac7c-c54e750723a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
