<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero_numeroCadastro</name>
   <tag></tag>
   <elementGuidId>8eb089b5-e79d-409c-97a3-79ac2742c288</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numeroCadastroRestaurante</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numeroCadastroRestaurante']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9fa8d98-21fb-4206-8db9-da5401907b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numeroCadastro</value>
      <webElementGuid>3cfc2b19-c118-488a-94db-8d6fc868502d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numeroCadastroRestaurante</value>
      <webElementGuid>8ec971bb-e474-4362-bc2f-9c75885f957b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f35cdb8a-4efa-4608-afe5-48f56418d930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1b8b0246-520d-4c60-8961-a65f3ce707e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numeroCadastroRestaurante&quot;)</value>
      <webElementGuid>9b68958f-ede4-4bdc-aa25-be86e0c5ed7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numeroCadastroRestaurante']</value>
      <webElementGuid>f10e91eb-984c-4814-bed1-1d58152f1942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[3]/input</value>
      <webElementGuid>1b95a95a-f2de-40da-80fb-4a25a556ac85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>afed3e4f-4ab0-4bbd-b21e-f2fdfa737646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'numeroCadastro' and @id = 'numeroCadastroRestaurante' and @type = 'text']</value>
      <webElementGuid>5efdbd9d-cced-4a87-9b09-e15a1e8fe410</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
