<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SegundaTeraQuartaQuintaSextaSbadoDomingo</name>
   <tag></tag>
   <elementGuidId>70c8b0d4-93de-4643-85b6-513d66934e8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;fimSemana&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='fimSemana']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>11c91d8f-615a-453b-8557-8d1b6cffd338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semana</value>
      <webElementGuid>a1b3bb30-14e4-4ce6-945f-ae4ef305c05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fimSemana</value>
      <webElementGuid>3148c0bb-f4e4-4265-8740-40907fe6f3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Segunda									
										Terça									
										Quarta									
										Quinta									
										Sexta									
										Sábado	
										Domingo

							</value>
      <webElementGuid>378562de-20cb-4ab5-b325-b4153005dad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formularioCadastroRestaurante&quot;)/div[7]/select[@class=&quot;semana&quot;]</value>
      <webElementGuid>640a1861-69d1-4530-9d36-5b849b07a9b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='fimSemana']</value>
      <webElementGuid>98d43522-dd29-48b7-87e7-10ab41a4c50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[7]/select[2]</value>
      <webElementGuid>3fde0880-38af-4dd0-8d4d-e9e4f650b87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Dias da semana:'])[1]/following::select[2]</value>
      <webElementGuid>73bf9406-b2f8-48e9-9861-5af04ebd1e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::select[1]</value>
      <webElementGuid>cecce149-a9cc-4220-8b29-ae7478a7e40c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>5efa0edf-bf6b-42e1-acec-bca0d90bb53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fimSemana' and (text() = '
										Segunda									
										Terça									
										Quarta									
										Quinta									
										Sexta									
										Sábado	
										Domingo

							' or . = '
										Segunda									
										Terça									
										Quarta									
										Quinta									
										Sexta									
										Sábado	
										Domingo

							')]</value>
      <webElementGuid>cf7aee82-2e5b-4e01-94f9-160855ebe4dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
