<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SegundaTeraQuartaQuintaSextaSbadoDomingo (1)</name>
   <tag></tag>
   <elementGuidId>3c2bc3fc-cee9-4313-8b9d-b7a8eb9af384</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;inicioSemana&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='inicioSemana']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1c400ac3-1d31-4272-ba6d-e7a3f268cc84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semana</value>
      <webElementGuid>54a0714c-7c7f-44cb-aaf7-f53fc585ed5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inicioSemana</value>
      <webElementGuid>cd139435-3032-4b82-a2da-3a1de61b2cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Segunda									
										Terça									
										Quarta									
										Quinta									
										Sexta									
										Sábado		
										Domingo
							</value>
      <webElementGuid>3592ff68-7b62-4818-9071-2188de1bc0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formularioCadastroRestaurante&quot;)/div[7]/select[@class=&quot;semana&quot;]</value>
      <webElementGuid>f6abd14a-d28b-4308-8274-8a6a0d095ae5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='inicioSemana']</value>
      <webElementGuid>131db8bc-21be-4571-9c9a-a18aa43b29aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[7]/select</value>
      <webElementGuid>92247803-1d15-465c-8b04-1382757d76e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Dias da semana:'])[1]/following::select[1]</value>
      <webElementGuid>e9480f71-a9a2-464e-a931-c5f9fce70c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::select[2]</value>
      <webElementGuid>075b0029-e648-42e7-9be7-9a72c6c412af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>cb0b98e8-04cd-4788-8d5c-efe553a68bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'inicioSemana' and (text() = '
										Segunda									
										Terça									
										Quarta									
										Quinta									
										Sexta									
										Sábado		
										Domingo
							' or . = '
										Segunda									
										Terça									
										Quarta									
										Quinta									
										Sexta									
										Sábado		
										Domingo
							')]</value>
      <webElementGuid>bb03585b-71c0-4bd4-b46a-8f0cbd6dbc79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
