<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SegundaTeraQuartaQuintaSextaSbadoDomingo_1</name>
   <tag></tag>
   <elementGuidId>3500d182-71a3-4ba7-b115-13339bb56d55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;fimSemana&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='fimSemana']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c6ab7c4c-8dd2-4b2e-a60b-d1e621c14a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semana</value>
      <webElementGuid>a1c63f97-5a51-4759-aab0-1a385e6eba45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fimSemana</value>
      <webElementGuid>58836a85-adec-4f41-96ad-260cdf7d83c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Segunda									
										Terça									
										Quarta									
										Quinta									
										Sexta									
										Sábado	
										Domingo

							</value>
      <webElementGuid>e8363166-f14e-44ae-8e8d-1f4807be29f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formularioCadastroRestaurante&quot;)/div[7]/select[@class=&quot;semana&quot;]</value>
      <webElementGuid>dacd0146-82b4-44e9-9730-c08923733ad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='fimSemana']</value>
      <webElementGuid>389eaea0-bc4a-4fc6-813a-baf3133cda36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[7]/select[2]</value>
      <webElementGuid>68511b08-5f8c-422b-9dca-375370b0869b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Dias da semana:'])[1]/following::select[2]</value>
      <webElementGuid>1c321865-9683-4340-90ac-803caff1041b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::select[1]</value>
      <webElementGuid>26790675-4ce5-4ae3-bd09-a092f8fda609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>17670f5e-b08d-42be-9250-325bb82265b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fimSemana' and (text() = '
										Segunda									
										Terça									
										Quarta									
										Quinta									
										Sexta									
										Sábado	
										Domingo

							' or . = '
										Segunda									
										Terça									
										Quarta									
										Quinta									
										Sexta									
										Sábado	
										Domingo

							')]</value>
      <webElementGuid>7b074b69-7284-4222-933e-9d53ccf9bfbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
