<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ALAPAMBACEDFESGOMAMTMSMGPAPBPRPEPIRR_4d941d (1)</name>
   <tag></tag>
   <elementGuidId>1b3d0f9c-e0d5-4cf9-8490-8fbaeac597c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;estadoCadastro&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='estadoCadastro']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b552bbc3-eaea-46a9-abea-8ee4ca5d2466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uf</value>
      <webElementGuid>c7ef9933-35ec-4686-92e5-e84d9a06acbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>estadoCadastro</value>
      <webElementGuid>d8949a44-95ab-4be3-9857-f4cf6e0161b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										AL
										AP									
										AM									
										BA									
										CE									
										DF									
										ES									
										GO									
										MA									
										MT									
										MS									
										MG									
										PA									
										PB									
										PR									
										PE									
										PI									
										RR									
										RO									
										RJ									
										RN									
										RS									
										SC									
										SP									
										SE									
										TO									 
							</value>
      <webElementGuid>41d40fa2-780d-4d44-9104-820432a862c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formularioCadastroRestaurante&quot;)/div[4]/select[@class=&quot;uf&quot;]</value>
      <webElementGuid>1536a75a-3699-477e-bedd-e58f60d7662f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='estadoCadastro']</value>
      <webElementGuid>6cd210c1-aea6-4d90-bfc6-3a71d7eb8905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formularioCadastroRestaurante']/div[4]/select</value>
      <webElementGuid>1df08460-9cd2-4aa1-a2ca-8249a2d6b49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*UF:'])[1]/following::select[1]</value>
      <webElementGuid>3a2373ec-bc5a-439a-84b8-d95649018b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Cidade:'])[1]/following::select[1]</value>
      <webElementGuid>3c6ed5c4-3cc4-424c-a6bd-57e88bd50324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Telefone:'])[1]/preceding::select[1]</value>
      <webElementGuid>a3cf2dbc-1c31-489e-866a-27e7c6e3149d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9ae23238-b09c-4f93-8585-bd6b32b23b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'estadoCadastro' and (text() = '
										AL
										AP									
										AM									
										BA									
										CE									
										DF									
										ES									
										GO									
										MA									
										MT									
										MS									
										MG									
										PA									
										PB									
										PR									
										PE									
										PI									
										RR									
										RO									
										RJ									
										RN									
										RS									
										SC									
										SP									
										SE									
										TO									 
							' or . = '
										AL
										AP									
										AM									
										BA									
										CE									
										DF									
										ES									
										GO									
										MA									
										MT									
										MS									
										MG									
										PA									
										PB									
										PR									
										PE									
										PI									
										RR									
										RO									
										RJ									
										RN									
										RS									
										SC									
										SP									
										SE									
										TO									 
							')]</value>
      <webElementGuid>d477a620-1249-4e46-92bf-f78ee4e52923</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
