<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_novo</name>
   <tag></tag>
   <elementGuidId>7cde88e8-de89-4395-a096-dac64c687c9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(25) > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='principal']/table/tbody/tr[25]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>51ac5ed2-43c2-4225-ae1e-887fc43b48f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>justify</value>
      <webElementGuid>3ab9bb29-73b9-4adb-8c2c-886b39bb74b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>novo</value>
      <webElementGuid>5b645256-9fdb-4660-88ea-e16c46a05f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;principal&quot;)/table[1]/tbody[1]/tr[25]/td[1]</value>
      <webElementGuid>d1a69148-a82d-405d-bd14-eb2cd17c18e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='principal']/table/tbody/tr[25]/td</value>
      <webElementGuid>59c1c81d-3d0f-461f-954e-2646089809c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De Segunda a Sábado'])[16]/following::td[2]</value>
      <webElementGuid>07cfc686-f32e-444d-a866-62f8f636c068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rua - no.200 - bairro - Rio de Janeiro - RJ'])[15]/following::td[5]</value>
      <webElementGuid>f5876dc9-2886-436b-90e3-b1f201856315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(00)2222-2222'])[1]/preceding::td[1]</value>
      <webElementGuid>7e75d696-436c-40fa-a82b-2bc575b51476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rua - no.100 - bairro - Minas Gerais - MG'])[1]/preceding::td[2]</value>
      <webElementGuid>64118655-b8ef-481c-b75f-ed2bfa1303e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='novo']/parent::*</value>
      <webElementGuid>4f04119a-04b1-47dd-941b-2631e5ccaf3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[25]/td</value>
      <webElementGuid>717a4324-c8d1-4e9f-b3d4-5ca9e19b7e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'novo' or . = 'novo')]</value>
      <webElementGuid>e5e95de8-11a7-422b-944b-e6df03fbe4e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
